"use client";

import { useState } from "react";
import { createMemoryEvent } from "@/actions/institutional-memory-actions";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Network, Loader2, CheckCircle2, AlertCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const PRODUCT_OPTIONS = [
  { value: "decision", label: "DecisionOS" },
  { value: "workflow", label: "WorkflowOS" },
  { value: "audit", label: "AuditOS" },
  { value: "localContent", label: "LocalContentOS" },
  { value: "contact", label: "LocalContactOS" },
  { value: "sales", label: "SalesOS" },
];

const EVENT_TYPE_OPTIONS = [
  { value: "linked", label: "مرتبط (Linked)" },
  { value: "references", label: "يشير إلى (References)" },
  { value: "evidence_for", label: "دليل لـ (Evidence For)" },
  { value: "supports", label: "يدعم (Supports)" },
  { value: "generated_by", label: "مُنشأ بواسطة (Generated By)" },
  { value: "approved_by", label: "معتمد من (Approved By)" },
  { value: "related_to", label: "متعلق بـ (Related To)" },
];

const RTL_OVERRIDE = { style: { direction: "rtl" as const, textAlign: "right" as const } };

export function LinkToInstMem({
  sourceProduct,
  sourceEntityId,
  sourceEntityName,
}: {
  sourceProduct: string;
  sourceEntityId: string;
  sourceEntityName: string;
}) {
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [result, setResult] = useState<"success" | "error" | null>(null);
  const [targetProduct, setTargetProduct] = useState("");
  const [targetEntityId, setTargetEntityId] = useState("");
  const [targetEntityType, setTargetEntityType] = useState("");
  const [eventType, setEventType] = useState("linked");
  const [description, setDescription] = useState("");

  async function handleSubmit() {
    if (!targetProduct || !targetEntityId) return;
    setSaving(true);
    setResult(null);
    const res = await createMemoryEvent({
      sourceProduct,
      sourceEntityId,
      sourceEntityType: sourceProduct + "_entity",
      targetProduct,
      targetEntityId,
      targetEntityType: targetProduct + "_entity",
      eventType,
      description: description || undefined,
    });
    setSaving(false);
    if (res.success) {
      setResult("success");
      setTimeout(() => { setOpen(false); setResult(null); resetForm(); }, 1500);
    } else {
      setResult("error");
    }
  }

  function resetForm() {
    setTargetProduct("");
    setTargetEntityId("");
    setTargetEntityType("");
    setEventType("linked");
    setDescription("");
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) { setResult(null); resetForm(); } }}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          <Network className="h-4 w-4 ml-1" />
          ربط بالذاكرة المؤسسية
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md" {...RTL_OVERRIDE}>
        <DialogHeader>
          <DialogTitle>ربط بالذاكرة المؤسسية</DialogTitle>
          <DialogDescription>
            أنشئ رابطاً بين هذا الكيان وكيان آخر عبر المنصة
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {/* Source (read-only) */}
          <div>
            <Label className="text-xs text-muted-foreground">المصدر</Label>
            <div className="flex items-center gap-2 mt-1">
              <Badge variant="secondary" className="text-xs">
                {sourceProduct}
              </Badge>
              <span className="text-sm font-medium truncate">{sourceEntityName}</span>
            </div>
          </div>

          {/* Target product */}
          <div>
            <Label htmlFor="targetProduct">المنتج الهدف</Label>
            <Select value={targetProduct} onValueChange={setTargetProduct}>
              <SelectTrigger id="targetProduct" className="mt-1">
                <SelectValue placeholder="اختر المنتج" />
              </SelectTrigger>
              <SelectContent>
                {PRODUCT_OPTIONS.map((p) => (
                  <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Target entity ID & type */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="targetId">معرف الكيان</Label>
              <Input
                id="targetId"
                value={targetEntityId}
                onChange={(e) => setTargetEntityId(e.target.value)}
                placeholder="entity-id"
                className="mt-1 ltr text-left"
              />
            </div>
            <div>
              <Label htmlFor="targetType">نوع الكيان</Label>
              <Input
                id="targetType"
                value={targetEntityType}
                onChange={(e) => setTargetEntityType(e.target.value)}
                placeholder="type"
                className="mt-1 ltr text-left"
              />
            </div>
          </div>

          {/* Event type */}
          <div>
            <Label htmlFor="eventType">نوع العلاقة</Label>
            <Select value={eventType} onValueChange={setEventType}>
              <SelectTrigger id="eventType" className="mt-1">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {EVENT_TYPE_OPTIONS.map((t) => (
                  <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Description */}
          <div>
            <Label htmlFor="desc">وصف (اختياري)</Label>
            <Textarea
              id="desc"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="وصف العلاقة..."
              className="mt-1"
              rows={3}
            />
          </div>

          {/* Result feedback */}
          {result === "success" && (
            <div className="flex items-center gap-2 text-sm text-green-600 bg-green-50 dark:bg-green-950/30 rounded-md px-3 py-2">
              <CheckCircle2 className="h-4 w-4" />
              تم الربط بنجاح ✓
            </div>
          )}
          {result === "error" && (
            <div className="flex items-center gap-2 text-sm text-red-600 bg-red-50 dark:bg-red-950/30 rounded-md px-3 py-2">
              <AlertCircle className="h-4 w-4" />
              فشل الربط — تحقق من معرف الكيان
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)} disabled={saving}>
            إلغاء
          </Button>
          <Button onClick={handleSubmit} disabled={saving || !targetProduct || !targetEntityId}>
            {saving && <Loader2 className="h-4 w-4 ml-1 animate-spin" />}
            {saving ? "جارٍ الربط..." : "ربط"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
