export const RISK_STRINGS = {
  error: {
    MODEL_NOT_FOUND: 'Risk model not found',
    ASSESSMENT_NOT_FOUND: 'Risk assessment not found',
    PROCEDURE_NOT_FOUND: 'Risk procedure not found',
    ORG_ID_REQUIRED: 'Organization ID is required',
    MODEL_NAME_REQUIRED: 'Risk model name is required',
    CATEGORIES_REQUIRED: 'At least one risk category is required',
    WEIGHTS_MUST_SUM_100: 'Category weights must sum to 100',
    CATEGORY_QUESTIONS_REQUIRED: 'Each category must have at least one question',
    MODEL_NOT_ACTIVE: 'Risk model is not active',
    MISSING_ANSWERS: 'Answers must cover all questions in the model',
    INVALID_ANSWER_VALUE: 'Answer values must be between 0 and 100',
    INVALID_TRANSITION: 'Assessment status does not allow this action',
    FETCH_FAILED: 'Failed to fetch risk data',
    CREATE_FAILED: 'Failed to create risk record',
    CROSS_ORG_ACCESS_DENIED: 'Access denied: resource belongs to a different organization',
    PROCEDURE_GENERATION_FAILED: 'Failed to generate risk procedures',
  },
  event: {
    MODEL_CREATED: 'Risk model created',
    ASSESSMENT_CREATED: 'Risk assessment created',
    ASSESSMENT_REVIEWED: 'Risk assessment reviewed',
    ASSESSMENT_APPROVED: 'Risk assessment approved',
    PROCEDURE_UPDATED: 'Risk procedure updated',
    PROCEDURES_GENERATED: 'Risk procedures generated',
  },
  riskLevel: {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
    CRITICAL: 'Critical',
  },
  riskResponse: {
    ACCEPT: 'Accept',
    MITIGATE: 'Mitigate',
    TRANSFER: 'Transfer',
    AVOID: 'Avoid',
  },
  procedure: {
    HIGH_STEPS: 3,
    MEDIUM_STEPS: 2,
    LOW_STEPS: 1,
  },
  ar: {
    error: {
      MODEL_NOT_FOUND: 'نموذج المخاطر غير موجود',
      ASSESSMENT_NOT_FOUND: 'تقييم المخاطر غير موجود',
      ORG_ID_REQUIRED: 'معرف المنظمة مطلوب',
      MODEL_NAME_REQUIRED: 'اسم نموذج المخاطر مطلوب',
      WEIGHTS_MUST_SUM_100: 'يجب أن مجموع أوزان الفئات يساوي 100',
    },
    riskLevel: {
      LOW: 'منخفض',
      MEDIUM: 'متوسط',
      HIGH: 'مرتفع',
      CRITICAL: 'حرج',
    },
    riskResponse: {
      ACCEPT: 'قبول',
      MITIGATE: 'تخفيف',
      TRANSFER: 'تحويل',
      AVOID: 'تجنب',
    },
  },
} as const
