import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "*.js",
    "*.mjs",
    "src/__tests__/**",
    "src/__mocks__/**",
    "prisma/**",
    "scripts/**",
    "**/*.test.ts",
    "src/components/audit/trial-balance/**",
    "src/components/audit/review/**",
    "src/components/audit/pilot/**",
    "src/lib/recommendation/**",
    "src/lib/simulation/**",
    "src/lib/decision/**",
    "src/actions/approval.ts",
    "src/actions/decisions.ts",
    "src/actions/decision-export.ts",
    "src/actions/decision-intelligence.ts",
    "src/actions/decision-learning.ts",
    "src/actions/decision-outcomes.ts",
    "src/actions/decision-sector.ts",
    "src/actions/decision-signals-alerts.ts",
    "src/actions/decision-templates.ts",
    "src/actions/simulation.ts",
    "src/actions/tender.ts",
    "src/lib/platform-audit.ts",
    "src/lib/decision-type-config.ts",
    "src/lib/recommendation/**",
    "src/lib/simulation/**",
    "src/lib/decision/**",
    "src/components/decisions/**",
    "src/lib/platform/**",
    "src/actions/decisions.ts",
    "src/actions/approval.ts",
    "src/actions/decision-export.ts",
    "src/actions/decision-intelligence.ts",
    "src/actions/decision-learning.ts",
    "src/actions/decision-outcomes.ts",
    "src/actions/decision-sector.ts",
    "src/actions/decision-signals-alerts.ts",
    "src/actions/decision-templates.ts",
    "src/actions/simulation.ts",
    "src/actions/tender.ts",
    "src/lib/platform-audit.ts",
    "src/lib/decision-type-config.ts",
    "src/lib/recommendation/**",
    "src/lib/simulation/**",
    "src/lib/decision/**",
    "src/app/(dashboard)/**",
  ]),
]);

export default eslintConfig;
