// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv ts-node @types/node @prisma/adapter-better-sqlite3 better-sqlite3
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: "file:./prisma/dev.db",
  },
});
