const mockPrisma = {
  // Knowledge Foundation (Phase 9)
  knowledgeFoundationVersion: {
    findMany: ({ orderBy, where, include } = {}) => [],
    findUnique: () => null,
    findUniqueOrThrow: (args) => ({ id: args?.where?.id ?? 'kfv-1', versionNumber: '1.0.0', status: 'DRAFT', notes: null, createdAt: new Date(), updatedAt: new Date(), createdById: 'user-1', approvedById: null, approvedAt: null, releasedById: null, releasedAt: null, activatedById: null, activatedAt: null, rollbackVersionId: null }),
    findFirst: () => null,
    count: () => 0,
    groupBy: () => [],
    create: (args) => ({ id: 'kfv-1', ...args?.data }),
    update: (args) => ({ ...args?.data, id: args?.where?.id }),
    updateMany: (args) => ({ count: 1 }),
    delete: () => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  knowledgeFoundationRelease: {
    findMany: () => [],
    findUnique: () => null,
    findUniqueOrThrow: () => null,
    findFirst: () => null,
    count: () => 0,
    create: (args) => ({ id: 'kfr-1', ...args?.data }),
    update: (args) => ({ ...args?.data, id: args?.where?.id }),
    delete: () => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  knowledgeFoundationDiff: {
    findMany: () => [],
    findUnique: () => null,
    findUniqueOrThrow: () => null,
    findFirst: () => null,
    count: () => 0,
    create: (args) => ({ id: 'kfd-1', ...args?.data }),
    upsert: (args) => ({ id: 'kfd-1', ...args?.create }),
    update: (args) => ({ ...args?.data, id: args?.where?.id }),
    delete: () => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  knowledgeFoundationVersionCandidate: {
    findMany: ({ where } = {}) => [],
    findFirst: () => null,
    count: ({ where } = {}) => 0,
    create: (args) => ({ id: 'kfvc-1', ...args?.data }),
    createMany: (args) => ({ count: args?.data?.length ?? 1 }),
    update: (args) => ({ ...args?.data, id: args?.where?.id }),
    updateMany: (args) => ({ count: 1 }),
    delete: (args) => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  knowledgeCandidate: {
    findMany: () => [],
    findUnique: () => null,
    findFirst: () => null,
    count: () => 0,
    create: (args) => ({ id: 'kc-1', ...args?.data }),
    update: (args) => ({ ...args?.data, id: args?.where?.id }),
    updateMany: (args) => ({ count: 1 }),
    delete: () => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  knowledgePromotionHistory: {
    findMany: () => [],
    findUnique: () => null,
    findFirst: () => null,
    count: () => 0,
    create: (args) => ({ id: 'kph-1', ...args?.data }),
    createMany: (args) => ({ count: args?.data?.length ?? 1 }),
    delete: () => ({}),
    deleteMany: () => ({ count: 0 }),
  },
  auditEngagement: { findMany: () => [], findUnique: () => null, count: () => 0, create: () => ({}), update: () => ({}), deleteMany: () => ({}), findFirst: () => null },
  auditOrganization: { findMany: () => [], findUnique: () => null, create: () => ({}), deleteMany: () => ({}) },
  auditUser: { findMany: () => [], findUnique: () => null, count: () => 0 },
  auditClient: { findMany: () => [], findUnique: () => null, create: () => ({}) },
  auditTrialBalance: { findFirst: () => null, findMany: () => [], create: () => ({}) },
  auditTrialBalanceLine: { findMany: () => [] },
  auditAccountMapping: { findMany: () => [], findUnique: () => null, count: () => 0, update: () => ({}) },
  auditFinancialStatement: { findMany: () => [], create: () => ({}) },
  auditDisclosureNote: { findMany: () => [] },
  auditEvidence: { findMany: () => [], count: () => 0 },
  auditEvidenceLink: { findMany: () => [], createMany: () => ({}) },
  auditFinding: { findMany: () => [], findUnique: () => null, createMany: () => ({}) },
  auditRecommendation: { findMany: () => [], findUnique: () => null },
  auditReviewComment: { findMany: () => [], findUnique: () => null, count: () => 0 },
  auditApprovalRecord: { findMany: () => [], count: () => 0 },
  auditPublicationPackage: { findFirst: () => null },
  auditEvent: { findMany: () => [], count: () => 0, create: () => ({}), createMany: () => ({}) },
  auditAiOutput: { findMany: () => [], create: () => ({}), count: () => 0 },
  auditCanonicalAccount: { findMany: () => [], findUnique: () => null, create: () => ({}) },
  auditValidationRun: { findFirst: () => null },
  organization: { create: () => ({}), deleteMany: () => ({}) },
  user: { create: () => ({}), deleteMany: () => ({}) },
  decision: { create: () => ({}), deleteMany: () => ({}) },
  tenderProfile: { deleteMany: () => ({}) },
  auditLog: { deleteMany: () => ({}) },
  decisionReport: { deleteMany: () => ({}) },
  decisionEvidence: { findMany: () => [], findUnique: () => null, count: () => 0, create: () => ({}), deleteMany: () => ({}), findFirst: () => null },
  approval: { deleteMany: () => ({}) },
  recommendation: { deleteMany: () => ({}) },
  simulationResult: { deleteMany: () => ({}) },
  scenario: { deleteMany: () => ({}) },
  risk: { deleteMany: () => ({}) },
  alternative: { deleteMany: () => ({}) },
  assumption: { deleteMany: () => ({}) },
  constraint: { deleteMany: () => ({}) },
  objective: { deleteMany: () => ({}) },
  pilotFeedback: { deleteMany: () => ({}) },
  pilotSignoff: { deleteMany: () => ({}) },
  productionBlocker: { deleteMany: () => ({}) },
  platformAuditLog: {
    findMany: () => [],
    findUnique: () => null,
    findFirst: () => null,
    count: () => 0,
    create: (args) => ({ id: 'pal-1', ...args?.data }),
    deleteMany: () => ({ count: 0 }),
  },
  $queryRaw: () => Promise.resolve([{ 1: 1 }]),
  $disconnect: () => Promise.resolve(),
  $transaction: (fn) => fn(mockPrisma),
}

module.exports = { prisma: mockPrisma, __esModule: true, default: mockPrisma }
