const mockPrisma = {
  auditEngagement: { findMany: () => [], findUnique: () => null, count: () => 0, create: () => ({}), update: () => ({}), deleteMany: () => ({}), findFirst: () => null },
  auditOrganization: { findMany: () => [], findUnique: () => null, create: () => ({}), deleteMany: () => ({}) },
  auditUser: { findMany: () => [], findUnique: () => null, count: () => 0 },
  auditClient: { findMany: () => [], findUnique: () => null, create: () => ({}) },
  auditTrialBalance: { findFirst: () => null, findMany: () => [], create: () => ({}) },
  auditTrialBalanceLine: { findMany: () => [] },
  auditAccountMapping: { findMany: () => [], findUnique: () => null, count: () => 0, update: () => ({}) },
  auditFinancialStatement: { findMany: () => [], create: () => ({}) },
  auditDisclosureNote: { findMany: () => [] },
  auditEvidence: { findMany: () => [], count: () => 0 },
  auditEvidenceLink: { findMany: () => [], createMany: () => ({}) },
  auditFinding: { findMany: () => [], findUnique: () => null, createMany: () => ({}) },
  auditRecommendation: { findMany: () => [], findUnique: () => null },
  auditReviewComment: { findMany: () => [], findUnique: () => null, count: () => 0 },
  auditApprovalRecord: { findMany: () => [], count: () => 0 },
  auditPublicationPackage: { findFirst: () => null },
  auditEvent: { findMany: () => [], count: () => 0, create: () => ({}), createMany: () => ({}) },
  auditAiOutput: { findMany: () => [], create: () => ({}), count: () => 0 },
  auditCanonicalAccount: { findMany: () => [], findUnique: () => null, create: () => ({}) },
  auditValidationRun: { findFirst: () => null },
  organization: { create: () => ({}), deleteMany: () => ({}) },
  user: { create: () => ({}), deleteMany: () => ({}) },
  decision: { create: () => ({}), deleteMany: () => ({}) },
  tenderProfile: { deleteMany: () => ({}) },
  auditLog: { deleteMany: () => ({}) },
  decisionReport: { deleteMany: () => ({}) },
  approval: { deleteMany: () => ({}) },
  recommendation: { deleteMany: () => ({}) },
  simulationResult: { deleteMany: () => ({}) },
  scenario: { deleteMany: () => ({}) },
  risk: { deleteMany: () => ({}) },
  alternative: { deleteMany: () => ({}) },
  assumption: { deleteMany: () => ({}) },
  constraint: { deleteMany: () => ({}) },
  objective: { deleteMany: () => ({}) },
  pilotFeedback: { deleteMany: () => ({}) },
  pilotSignoff: { deleteMany: () => ({}) },
  productionBlocker: { deleteMany: () => ({}) },
  $queryRaw: () => Promise.resolve([{ 1: 1 }]),
  $disconnect: () => Promise.resolve(),
  $transaction: (fn: Function) => fn(mockPrisma),
}

module.exports = { prisma: mockPrisma, __esModule: true, default: mockPrisma }
