export const ORG_STRINGS = {
  error: {
    ORG_NOT_FOUND: 'Organization not found',
    PARENT_ORG_NOT_FOUND: 'Parent organization not found',
    HIERARCHY_NODE_EXISTS: 'Hierarchy node already exists for this organization',
    CIRCULAR_HIERARCHY: 'Cannot set parent: would create circular hierarchy',
    SELF_PARENT: 'An organization cannot be its own parent',
    NODE_NOT_FOUND: 'Hierarchy node not found',
    SETTING_KEY_REQUIRED: 'Setting key is required',
    SETTING_VALUE_REQUIRED: 'Setting value is required',
    ORG_ID_REQUIRED: 'Organization ID is required',
    USER_ID_REQUIRED: 'User ID is required',
    EVENT_TYPE_REQUIRED: 'Event type is required',
    DESCRIPTION_REQUIRED: 'Event description is required',
    FETCH_FAILED: 'Failed to fetch organization data',
    CREATE_FAILED: 'Failed to create organization node',
    UPDATE_FAILED: 'Failed to update organization setting',
    DELETE_FAILED: 'Failed to delete organization setting',
    HEALTH_CHECK_FAILED: 'Failed to calculate organization health',
  },
  event: {
    NODE_CREATED: 'Organization hierarchy node created',
    SETTING_UPDATED: 'Organization setting updated',
    SETTING_DELETED: 'Organization setting deleted',
    EVENT_RECORDED: 'Organization lifecycle event recorded',
    HEALTH_CALCULATED: 'Organization health score calculated',
  },
  health: {
    SETTINGS_CONFIGURED: 'Settings configured',
    ACTIVE_USERS: 'Active users present',
    HAS_HIERARCHY: 'Hierarchy configured',
    RECENT_ACTIVITY: 'Recent activity within 30 days',
    NO_CRITICAL_EVENTS: 'No critical lifecycle events',
  },
  setting: {
    DEFAULT_LOCALE: 'Default locale',
    TIMEZONE: 'Timezone',
    MAX_USERS: 'Maximum users',
    REQUIRE_MFA: 'Require multi-factor authentication',
    AUDIT_RETENTION_DAYS: 'Audit retention period (days)',
    CONTENT_APPROVAL_REQUIRED: 'Content approval required',
  },
  ar: {
    error: {
      ORG_NOT_FOUND: 'المنظمة غير موجودة',
      PARENT_ORG_NOT_FOUND: 'المنظمة الأصلية غير موجودة',
      CIRCULAR_HIERARCHY: 'لا يمكن تعيين الأصل: سيؤدي إلى تسلسل هرمي دائري',
      SELF_PARENT: 'لا يمكن للمنظمة أن تكون أصلاً لنفسها',
      NODE_NOT_FOUND: 'عقدة التسلسل الهرمي غير موجودة',
      SETTING_KEY_REQUIRED: 'مفتاح الإعداد مطلوب',
      SETTING_VALUE_REQUIRED: 'قيمة الإعداد مطلوبة',
      ORG_ID_REQUIRED: 'معرف المنظمة مطلوب',
      EVENT_TYPE_REQUIRED: 'نوع الحدث مطلوب',
      DESCRIPTION_REQUIRED: 'وصف الحدث مطلوب',
      FETCH_FAILED: 'فشل في جلب بيانات المنظمة',
      CREATE_FAILED: 'فشل في إنشاء عقدة المنظمة',
      UPDATE_FAILED: 'فشل في تحديث إعداد المنظمة',
      DELETE_FAILED: 'فشل في حذف إعداد المنظمة',
      HEALTH_CHECK_FAILED: 'فشل في حساب صحة المنظمة',
    },
    event: {
      NODE_CREATED: 'تم إنشاء عقدة التسلسل الهرمي للمنظمة',
      SETTING_UPDATED: 'تم تحديث إعداد المنظمة',
      SETTING_DELETED: 'تم حذف إعداد المنظمة',
      EVENT_RECORDED: 'تم تسجيل حدث دورة حياة المنظمة',
      HEALTH_CALCULATED: 'تم حساب درجة صحة المنظمة',
    },
    health: {
      SETTINGS_CONFIGURED: 'الإعدادات مهيأة',
      ACTIVE_USERS: 'المستخدمون النشطون موجودون',
      HAS_HIERARCHY: 'التسلسل الهرمي مهيأ',
      RECENT_ACTIVITY: 'نشاط حديث خلال 30 يوماً',
      NO_CRITICAL_EVENTS: 'لا توجد أحداث دورة حياة حرجة',
    },
    setting: {
      DEFAULT_LOCALE: 'اللغة الافتراضية',
      TIMEZONE: 'المنطقة الزمنية',
      MAX_USERS: 'الحد الأقصى للمستخدمين',
      REQUIRE_MFA: 'طلب التحقق متعدد العوامل',
      AUDIT_RETENTION_DAYS: 'فترة الاحتفاظ بالتدقيق (أيام)',
      CONTENT_APPROVAL_REQUIRED: 'الموافقة على المحتوى مطلوبة',
    },
  },
} as const
