export const BRIDGE_STRINGS = {
  error: {
    SOURCE_REQUIRED: 'Source product is required',
    EVENT_ID_REQUIRED: 'Event ID is required',
    ORG_ID_REQUIRED: 'Organization ID is required',
    RULE_NAME_REQUIRED: 'Bridge rule name is required',
    RULE_NOT_FOUND: 'Bridge rule not found',
    RULE_NOT_ACTIVE: 'Bridge rule is not active',
    RULE_SOURCE_REQUIRED: 'Bridge rule source is required',
    ADAPTER_NOT_FOUND: 'No bridge adapter registered for source',
    EVENT_NOT_FOUND: 'Source event not found',
    BRIDGE_FAILED: 'Bridge write operation failed',
    RETRY_FAILED: 'Retry operation failed',
    MAX_RETRIES_EXCEEDED: 'Maximum retry attempts exceeded',
    CROSS_ORG_ACCESS: 'Access denied: resource belongs to a different organization',
    INVALID_FIELD_MAPPINGS: 'Field mappings must be a valid JSON object',
    INVALID_EVENT_TYPE_FILTER: 'Event type filter must be "*" or a comma-separated list',
  },
  event: {
    BRIDGE_CREATED: 'Audit event bridged to platform log',
    RULE_CREATED: 'Audit bridge rule created',
    RULE_UPDATED: 'Audit bridge rule updated',
    RULE_DELETED: 'Audit bridge rule deleted',
    BULK_BRIDGE_COMPLETED: 'Bulk bridge operation completed',
    RETRY_FAILED_ATTEMPTED: 'Retry of failed bridge entries attempted',
  },
  ar: {
    error: {
      SOURCE_REQUIRED: 'المنتج المصدر مطلوب',
      EVENT_ID_REQUIRED: 'معرف الحدث مطلوب',
      ORG_ID_REQUIRED: 'معرف المنظمة مطلوب',
      RULE_NAME_REQUIRED: 'اسم قاعدة الربط مطلوب',
      RULE_NOT_FOUND: 'قاعدة الربط غير موجودة',
      RULE_NOT_ACTIVE: 'قاعدة الربط غير نشطة',
      ADAPTER_NOT_FOUND: 'لا يوجد محول ربط مسجل لهذا المصدر',
      EVENT_NOT_FOUND: 'الحدث المصدر غير موجود',
      BRIDGE_FAILED: 'فشلت عملية الربط',
      RETRY_FAILED: 'فشلت عملية إعادة المحاولة',
      MAX_RETRIES_EXCEEDED: 'تم تجاوز الحد الأقصى لمحاولات إعادة المحاولة',
      CROSS_ORG_ACCESS: 'وصول مرفوض: المورد ينتمي إلى منظمة مختلفة',
      INVALID_FIELD_MAPPINGS: 'يجب أن تكون تعيينات الحقول كائن JSON صالحًا',
    },
    event: {
      BRIDGE_CREATED: 'تم ربط حدث التدقيق في سجل المنصة',
      RULE_CREATED: 'تم إنشاء قاعدة ربط التدقيق',
      RULE_UPDATED: 'تم تحديث قاعدة ربط التدقيق',
      RULE_DELETED: 'تم حذف قاعدة ربط التدقيق',
      BULK_BRIDGE_COMPLETED: 'اكتملت عملية الربط الجماعي',
      RETRY_FAILED_ATTEMPTED: 'تمت محاولة إعادة ربط الإدخالات الفاشلة',
    },
  },
} as const
