// Governance bridge — re-exports the full governance API surface from its
// canonical location so that consumers can import via `@/lib/kernel` instead
// of reaching into `@/lib/governance` directly.

export {
  canMutateByLineage,
  actorDisplayName,
  canTransitionApprovalState,
  requireHumanApproval,
  isFinalizationAllowed,
  getApprovalBlockingReasons,
  evaluateEscalation,
  getEscalationLevel,
  getEscalationMessage,
  requiresHumanResolution,
  createDraftProvenance,
  attachEvidenceStatus,
  markReviewRequired,
  markEscalated,
  markApprovedByHuman,
  explainProvenance,
  getGovernanceContext,
  listSupportedGovernanceTasks,
  requiresHumanApproval,
  buildStatementDraftingPrompt,
  buildMappingRecommendationPrompt,
  buildEvidenceReviewPrompt,
  buildAuditFindingPrompt,
  buildAccountClassificationPrompt,
  buildCommercialClaimReviewPrompt,
} from "@/lib/governance";

export type {
  GovernanceTaskType,
  ApprovalState,
  EscalationLevel,
  EscalationTrigger,
  EvidenceStatus,
  OutputBoundary,
  PromptLayer,
  GovernanceContext,
  ProvenanceMetadata,
  EscalationResult,
  EscalationRecord,
  DoctrineReference,
  GovernanceReference,
  EvidenceRequirement,
  PromptAssemblyResult,
  PromptLayerContent,
  StatementDraftingPromptInput,
  MappingRecommendationPromptInput,
  EvidenceReviewPromptInput,
  AuditFindingPromptInput,
  CommercialClaimPromptInput,
} from "@/lib/governance";
