export type { Principal, TenantContext, KernelResult, PaginatedResult, KernelHealth, KernelHealthReport, ProductRoute, ProductSchema } from "./types";
export type { PrincipalRole, ResourceType, AccessAction } from "./types";

export type { IIdentityService, CurrentUserInfo } from "./contracts/identity";
export type { ITenantService, TenantValidationResult } from "./contracts/tenant";
export type { IWorkflowEngine, WorkflowTransitionResult, WorkflowTemplate, WorkflowTransitionAction } from "./contracts/workflow";
export type { IPolicyEngine, PolicyEvaluationRequest, PolicyEvaluationResult } from "./contracts/policy";
export type { IEvidenceService, EvidenceItem, CreateEvidenceInput } from "./contracts/evidence";
export type { IAIGateway, AIRequest, AIResponse, AIProviderInfo, AIProvider, AITaskType } from "./contracts/ai-gateway";
export type { IEventBus, DomainEvent, EventHandler, EventDomain } from "./contracts/event-bus";
export type { IAuditLedger, AuditEntry } from "./contracts/audit-ledger";
export type { INotificationService, NotificationMessage, NotificationPreferences, NotificationChannel, NotificationPriority } from "./contracts/notification";
export type { IFilesService, FileMetadata } from "./contracts/files";
export type { ISearchService, SearchResult } from "./contracts/search";
export type { IKnowledgeService, KnowledgeItem } from "./contracts/knowledge";
export type { IAutomationService, AutomationRule, AutomationRun, AutomationTrigger } from "./contracts/automation";
export type { ISchedulingService, ScheduledJob, ScheduleFrequency } from "./contracts/scheduling";
export type { IFeatureFlagService, FeatureFlag, FlagVariant } from "./contracts/feature-flags";
export type { ISecretsVault, SecretValue } from "./contracts/secrets";
export type { IEncryptionService } from "./contracts/encryption";
export type { ICacheLayer, CacheEntry } from "./contracts/cache";

export type { ProductPlugin, PluginDependencies } from "./plugin/product-plugin";
export { ProductRegistry } from "./plugin/product-registry";

export { Kernel, initializeKernel } from "./bootstrap";
export { enforce, isAllowed, isPlatformAdmin, assertPlatformAdmin, resolveCallerTenantId } from "./authorization";
export { getCurrentUser, hasRequiredRole, isExpectedAccessDeniedError, isAdmin, encrypt, decrypt } from "./auth";
export type { CurrentUser, RequiredRole } from "./auth";
export { isEnabled, requireEnabled, getFlag } from "./feature-flags";
export { getCachedOrFetch, invalidateCacheByPrefix, invalidateDashboardCaches, warmDashboardCaches } from "./cache";
export { prisma } from "./prisma";

// ── AuditOS bridge (re-exports from kernel/audit.ts) ───────────
export {
  getAuditActor,
  requireRole,
  isUsingDemoFallback,
  ensureAuditUserProvisioned,
  canDraft,
  canReview,
  canApprove,
  assertEngagementAccess,
  assertClientAccess,
  assertOrganizationAccess,
  TenantAccessError,
  recordAuditOsAuditEvent,
  enforceAuditRateLimit,
  resetRateLimit,
  getEngagement,
  getTrialBalance,
  getMappings,
  getFinancialStatements,
  getDisclosureNotes,
  getEvidence,
  getEvidencePaginated,
  getMissingEvidence,
  getFindings,
  getFindingsPaginated,
  getRecommendations,
  getRecommendationsPaginated,
  getReviewComments,
  getOpenReviewCount,
  getApprovalRecords,
  getApprovalStatus,
  getAuditEvents,
  getPublicationPackage,
  getValidationRun,
  getEngagementWorkflowStatus,
  getCanonicalAccounts,
  getTrialBalanceLines,
  getDashboardSummary,
  getEngagements,
  getAuditUsers,
  getAISuggestions,
  recordAuditEvent,
  createEngagement,
  uploadTrialBalance,
  getTraceability,
  updateManualMapping,
  getAccountMappingById,
  createReviewComment,
  updateReviewCommentStatus,
  createApprovalRecord,
  publishEngagement,
  archiveEngagement,
  restoreEngagement,
  updateEngagementPresentationProfile,
  runValidation,
  disposeValidationIssue,
  createFinding,
  updateFindingStatus,
  createRecommendation,
  updateRecommendationStatus,
  createEvidence,
  updateEvidenceState,
  updateEvidenceStateWithEvent,
  updateEvidenceStorageService,
  linkEvidenceToEntity,
  createAIOutput,
  updateAIOutputStatus,
  generateDraftNotes,
  acceptDraftNote,
  generateEvidenceSuggestions,
  acceptEvidenceSuggestion,
  generateFindingDrafts,
  acceptFindingDraft,
  generateRecommendationDrafts,
  acceptRecommendationDraft,
  generateAnalyticalReview,
  createPilotFeedback,
  updatePilotFeedbackStatus,
  getPilotFeedback,
  createProductionBlocker,
  updateProductionBlockerStatus,
  getProductionBlockers,
  createOrUpdatePilotSignoff,
  getPilotSignoffChecklist,
  confirmMapping,
  confirmAllSuggestedMappings,
  getUnmappedAccounts,
  getEquityStatementLines,
  getFinding,
  getRecommendation,
  acceptAISuggestion,
  updateNoteStatus,
  getAIOutputsForEntity,
  getFullTraceability,
  createEvidenceWithStorage,
  buildProvenanceMetadata,
  mapEngagementStatusToApprovalState,
  mapFindingStatusToApprovalState,
  mapRecommendationStatusToApprovalState,
  getGovernanceAuditMetadata,
  checkPublicationGovernance,
  evaluateFindingEscalation,
  evaluateEvidenceEscalation,
  buildEvidenceRequirementsFromEvidenceList,
  getNextWorkflowAction,
  getWorkflowProgressStep,
  getEngagementStatusLabel,
  getApprovalStatusLabel,
  getOperatorStatusDisplay,
  APPROVAL_STATUS_LABELS,
  ENGAGEMENT_STATUS_LABELS,
  evaluateTabGate,
  evaluateAllTabGates,
  isTabAccessible,
  extractRuleCitations,
  formatRuleCitationMarker,
  RULE_CITATION_PREFIX,
  evaluateEngagementArchival,
  ARCHIVABLE_ENGAGEMENT_STATUSES,
  listArchivedEngagements,
  calculatePerformanceMateriality,
  classifyBalanceMateriality,
  isScanRejected,
  scanEvidenceFile,
  getStorageProvider,
  buildStorageKey,
  pingClamAv,
  scanBufferWithClamAv,
  isFsV2Enabled,
  isReportingGraphEnabled,
  GENERIC_PRESENTATION_POLICY_V1,
  SHALFA_PILOT_PRESENTATION_POLICY_V1,
  BUILTIN_PRESENTATION_POLICIES,
  PROFILE_DEFAULT_POLICY_SLUG,
  getBuiltinPolicyBySlug,
  parsePresentationPolicyRules,
  policyUsesAuditedHeadlineRules,
  listPresentationPoliciesForOrganization,
  getPresentationPolicyRulesById,
  createOrgPresentationPolicyFromTemplate,
  updateOrgPresentationPolicy,
  assignPresentationPolicyToEngagement,
  listPresentationPolicyTemplates,
} from "./audit";
export type {
  AuditActor,
  AuditOsAuditInput,
  RateLimitCategory,
  NextWorkflowAction,
  OperatorStatusTone,
  OperatorStatusDisplay,
  ArchivedEngagementRow,
  ArchivalEligibility,
  TabGateResult,
  WorkflowContext,
  ReportingGraph,
  ReportingGraphNode,
  ReportingGraphNodeType,
  ReportingGraphEdgeType,
  ReportingGraphEdge,
  ReportingGraphStats,
  GraphBuildInput,
  GraphSnapshotRecord,
  AuditAIActorContext,
  PresentationPolicyRules,
  ResolvedPresentationContext,
  PresentationPolicySummary,
  PresentationPolicyEditableFields,
  PresentationProfileRebuildStatus,
  PresentationProfileRebuildResult,
} from "./audit";
