"use client";

import { useCallback, useEffect, useState } from "react";
import { getSignalsAction } from "@/actions/decision-signals-alerts";
import { acknowledgeSignalAction } from "@/actions/decision-signals-alerts";
import { useParams } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";

type Signal = {
  id: string;
  decisionId: string;
  source: string;
  referenceId: string;
  signalType: string;
  description: string;
  severity: string;
  status: string;
  generatedBy: string;
  acknowledgedBy: string | null;
  acknowledgedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

const severityColor: Record<string, string> = {
  INFO: "bg-blue-100 text-blue-800",
  LOW: "bg-green-100 text-green-800",
  MEDIUM: "bg-yellow-100 text-yellow-800",
  HIGH: "bg-red-100 text-red-800",
};

const statusColor: Record<string, string> = {
  NEW: "bg-gray-100 text-gray-800",
  ACKNOWLEDGED: "bg-green-100 text-green-800",
};

export default function SignalsPage() {
  const params = useParams();
  const decisionId = params.id as string;
  const [signals, setSignals] = useState<Signal[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadSignals = useCallback(async (showLoading = true) => {
    if (showLoading) {
      setLoading(true);
    }

    const result = await getSignalsAction(decisionId);
    if (result.error) {
      setError(result.error);
    } else if (result.data) {
      setSignals(result.data as Signal[]);
    }
    setLoading(false);
  }, [decisionId]);

  useEffect(() => {
    const timeout = setTimeout(() => {
      void loadSignals(false);
    }, 0);

    return () => clearTimeout(timeout);
  }, [loadSignals]);

  async function handleAcknowledge(signalId: string) {
    const result = await acknowledgeSignalAction(decisionId, signalId);
    if (result.success) {
      loadSignals();
    }
  }

  if (loading) return <div className="p-6">Loading signals...</div>;
  if (error) return <div className="p-6 text-red-600">{error}</div>;

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Monitoring Signals</h1>
      <p className="text-sm text-muted-foreground">
        System-generated signals that require monitoring. Signals are automatically generated and cannot be manually created.
      </p>

      {signals.length === 0 ? (
        <Card>
          <CardContent className="pt-6">
            <p className="text-center text-muted-foreground">No signals found.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {signals.map((signal) => (
            <Card key={signal.id}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-lg">{signal.signalType}</CardTitle>
                  <div className="flex gap-2">
                    <Badge className={severityColor[signal.severity] || ""}>
                      {signal.severity}
                    </Badge>
                    <Badge className={statusColor[signal.status] || ""}>
                      {signal.status}
                    </Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm">{signal.description}</p>
                <div className="flex gap-4 text-xs text-muted-foreground">
                  <span>Source: {signal.source}</span>
                  <span>Reference: {signal.referenceId}</span>
                  <span>Generated by: {signal.generatedBy}</span>
                  <span>Created: {format(new Date(signal.createdAt), "PPp")}</span>
                </div>
                {signal.status === "NEW" && (
                  <Button
                    size="sm"
                    onClick={() => handleAcknowledge(signal.id)}
                  >
                    Acknowledge
                  </Button>
                )}
                {signal.acknowledgedAt && (
                  <p className="text-xs text-muted-foreground">
                    Acknowledged at {format(new Date(signal.acknowledgedAt), "PPp")}
                  </p>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
