export const ADV_STRINGS = {
  error: {
    TEMPLATE_NOT_FOUND: 'Workflow template not found',
    TEMPLATE_NAME_REQUIRED: 'Template name is required',
    TEMPLATE_STEPS_EMPTY: 'Template must have at least one step',
    STEP_ORDER_INVALID: 'Step order must be a non-negative integer',
    STEP_TITLE_REQUIRED: 'Each step must have a title',
    STEP_TASK_TYPE_REQUIRED: 'Each step must have a task type',
    SCHEDULE_NOT_FOUND: 'Schedule not found',
    SCHEDULE_NAME_REQUIRED: 'Schedule name is required',
    INVALID_RECURRENCE: 'Recurrence must be DAILY, WEEKLY, or MONTHLY',
    ROLE_CONFIG_NOT_FOUND: 'Role configuration not found',
    ROLE_SLUG_REQUIRED: 'Role slug is required',
    CONFIDENCE_THRESHOLD_INVALID: 'Confidence threshold must be between 0 and 1',
    AUTO_ASSIGN_INVALID: 'Auto-assign threshold must be non-negative',
    MAX_TASKS_INVALID: 'Max tasks per day must be greater than 0',
    ORG_ID_REQUIRED: 'Organization ID is required',
    USER_ID_REQUIRED: 'User ID is required',
    TEMPLATE_INACTIVE: 'Cannot instantiate an inactive template',
    SCHEDULE_INACTIVE: 'Schedule is inactive',
    CONTEXT_VARIABLE_MISSING: 'Required context variable not provided',
    CREATE_TEMPLATE_FAILED: 'Failed to create workflow template',
    CREATE_SCHEDULE_FAILED: 'Failed to create schedule',
    CREATE_ROLE_CONFIG_FAILED: 'Failed to create role configuration',
    FETCH_FAILED: 'Failed to fetch data',
    PROCESS_SCHEDULES_FAILED: 'Failed to process due schedules',
    GET_STATS_FAILED: 'Failed to get task statistics',
  },
  event: {
    WORKFLOW_TEMPLATE_CREATED: 'Workflow template created',
    WORKFLOW_INSTANTIATED: 'Workflow instantiated from template',
    SCHEDULE_CREATED: 'Recurring schedule created',
    SCHEDULE_PROCESSED: 'Due schedule processed',
    ROLE_CONFIG_CREATED: 'AI role configuration created',
    TASKS_CREATED_FROM_SCHEDULE: 'Tasks created from schedule',
  },
  ar: {
    error: {
      TEMPLATE_NOT_FOUND: 'قالب سير العمل غير موجود',
      TEMPLATE_NAME_REQUIRED: 'اسم القالب مطلوب',
      TEMPLATE_STEPS_EMPTY: 'يجب أن يحتوي القالب على خطوة واحدة على الأقل',
      SCHEDULE_NOT_FOUND: 'الجدول غير موجود',
      SCHEDULE_NAME_REQUIRED: 'اسم الجدول مطلوب',
      INVALID_RECURRENCE: 'يجب أن يكون التكرار يومي أو أسبوعي أو شهري',
      ROLE_CONFIG_NOT_FOUND: 'إعدادات الدور غير موجودة',
      ROLE_SLUG_REQUIRED: 'معرف الدور مطلوب',
      ORG_ID_REQUIRED: 'معرف المنظمة مطلوب',
    },
  },
} as const
