import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";
import type { ScoringResult } from "./types";

export interface LocalContentExportInput {
  projectName: string;
  reportingPeriod: string;
  generatedBy: string;
  generatedAt: string;
  reviewStatus: string;
  approvalStatus: string;
  score: ScoringResult;
  disclaimer: string;
}

export interface LocalContentExportResult {
  format: "pdf" | "xlsx";
  filename: string;
  mimeType: string;
  content: string | Buffer;
}

const DISCLAIMER_LINES = [
  "هذا التقرير مولّد بواسطة LocalContentOS تحت AQLIYA.",
  "يمثل تقييم محتوى محلي محكوم تمت مراجعته واعتماده.",
  "هذا ليس تقرير امتثال نظامي معتمد من جهة تنظيمية.",
  "AI assists. Humans decide. Evidence governs.",
];

export async function buildAssessmentSummaryPDF(
  input: LocalContentExportInput,
): Promise<LocalContentExportResult> {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 40, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `Local Content Assessment - ${input.projectName}`,
      Author: "AQLIYA LocalContentOS",
      Subject: "Local Content Assessment Report",
      Creator: "AQLIYA LocalContentOS",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const endPromise = new Promise<void>((resolve) =>
    doc.on("end", () => resolve()),
  );

  doc.fontSize(16).font("Helvetica-Bold").text("LocalContentOS", {
    align: "center",
  });
  doc.fontSize(12).font("Helvetica").text("Local Content Assessment Report", {
    align: "center",
  });
  doc.moveDown(0.8);

  doc.fontSize(9).font("Helvetica");
  doc.text(`Project: ${input.projectName}`);
  doc.text(`Reporting Period: ${input.reportingPeriod}`);
  doc.text(`Generated: ${input.generatedAt}`);
  doc.text(`Generated by: ${input.generatedBy}`);
  doc.text(`Review Status: ${input.reviewStatus || "Pending"}`);
  doc.text(`Approval Status: ${input.approvalStatus || "Pending"}`);
  doc.moveDown(0.6);

  doc.fontSize(11).font("Helvetica-Bold").text("Score Summary");
  doc.moveDown(0.2);
  doc.fontSize(9).font("Helvetica");
  doc.text(`Total Spend: SAR ${input.score.totalSpend.toLocaleString()}`);
  doc.text(
    `Local Content Percentage: ${input.score.localContentPercentage.toFixed(1)}%`,
  );
  doc.text(`Local Spend: SAR ${input.score.localSpend.toLocaleString()}`);
  doc.text(
    `Non-Local Spend: SAR ${input.score.nonLocalSpend.toLocaleString()}`,
  );
  doc.moveDown(0.6);

  doc.fontSize(11).font("Helvetica-Bold").text("Suppliers");
  doc.moveDown(0.2);
  doc.fontSize(9).font("Helvetica");
  doc.text(`Total: ${input.score.supplierCounts.total}`);
  doc.text(`Local: ${input.score.supplierCounts.local}`);
  doc.text(`Non-Local: ${input.score.supplierCounts.nonLocal}`);
  doc.text(`Mixed: ${input.score.supplierCounts.mixed}`);
  doc.text(`Unclassified: ${input.score.supplierCounts.unclassified}`);
  doc.moveDown(0.6);

  doc.fontSize(11).font("Helvetica-Bold").text("Evidence");
  doc.moveDown(0.2);
  doc.fontSize(9).font("Helvetica");
  doc.text(`Total: ${input.score.evidenceStats.total}`);
  doc.text(`Verified: ${input.score.evidenceStats.verified}`);
  doc.text(
    `Coverage: ${input.score.evidenceStats.coveragePercentage.toFixed(0)}%`,
  );
  doc.moveDown(0.6);

  doc.fontSize(11).font("Helvetica-Bold").text("Findings");
  doc.moveDown(0.2);
  doc.fontSize(9).font("Helvetica");
  doc.text(`Total: ${input.score.findingStats.total}`);
  for (const [severity, count] of Object.entries(
    input.score.findingStats.bySeverity,
  )) {
    doc.text(`  ${severity}: ${count}`);
  }
  doc.moveDown(1);

  const range = doc.bufferedPageRange();
  if (range && range.count > 0) {
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).fillColor("#888888").font("Helvetica");
      doc.text(
        `AQLIYA LocalContentOS — Page ${i + 1}`,
        50,
        doc.page.height - 50 - 10,
        { align: "center", width: 495 },
      );
    }
  }

  doc.end();
  await endPromise;

  const buffer = Buffer.concat(chunks);

  return {
    format: "pdf",
    filename: `local_content_assessment_${input.reportingPeriod.replace(/\s+/g, "_")}.pdf`,
    mimeType: "application/pdf",
    content: buffer,
  };
}

export async function buildSpendClassificationXLSX(
  input: LocalContentExportInput,
): Promise<LocalContentExportResult> {
  const wb = XLSX.utils.book_new();
  const data: string[][] = [];

  data.push(["Category", "Supplier", "Amount (SAR)", "Local %", "Locality"]);
  data.push(["Score Summary", "", "", "", ""]);
  data.push(["Total Spend", "", `${input.score.totalSpend}`, "", ""]);
  data.push([
    "Local Content %",
    "",
    `${input.score.localContentPercentage.toFixed(1)}`,
    "",
    "",
  ]);
  data.push(["Local Spend", "", `${input.score.localSpend}`, "", ""]);
  data.push(["Non-Local Spend", "", `${input.score.nonLocalSpend}`, "", ""]);
  data.push([""]);
  data.push(["Evidence Coverage", "", "", "", ""]);
  data.push([
    "Coverage",
    "",
    `${input.score.evidenceStats.coveragePercentage.toFixed(0)}%`,
    "",
    "",
  ]);
  data.push(["Verified", "", `${input.score.evidenceStats.verified}`, "", ""]);
  data.push(["Total", "", `${input.score.evidenceStats.total}`, "", ""]);
  data.push([""]);
  data.push([input.disclaimer]);

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws["!cols"] = [
    { wch: 25 },
    { wch: 20 },
    { wch: 18 },
    { wch: 12 },
    { wch: 12 },
  ];
  XLSX.utils.book_append_sheet(wb, ws, "Spend Classification");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;

  return {
    format: "xlsx",
    filename: `spend_classification_${input.reportingPeriod.replace(/\s+/g, "_")}.xlsx`,
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    content: buffer,
  };
}

export async function buildEvidenceIndexXLSX(
  input: LocalContentExportInput,
): Promise<LocalContentExportResult> {
  const wb = XLSX.utils.book_new();
  const data: string[][] = [];

  data.push(["Evidence Type", "Status", "Count"]);
  data.push(["Verified", "", `${input.score.evidenceStats.verified}`]);
  data.push(["Reviewed", "", `${input.score.evidenceStats.reviewed}`]);
  data.push(["Uploaded", "", `${input.score.evidenceStats.uploaded}`]);
  data.push(["Linked", "", `${input.score.evidenceStats.linked}`]);
  data.push(["Rejected", "", `${input.score.evidenceStats.rejected}`]);
  data.push(["Missing", "", `${input.score.evidenceStats.missing}`]);
  data.push(["Total", "", `${input.score.evidenceStats.total}`]);
  data.push([""]);
  data.push([input.disclaimer]);

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws["!cols"] = [{ wch: 25 }, { wch: 12 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(wb, ws, "Evidence Index");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;

  return {
    format: "xlsx",
    filename: `evidence_index_${input.reportingPeriod.replace(/\s+/g, "_")}.xlsx`,
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    content: buffer,
  };
}

export function formatReviewStatusForExport(
  latestReview: { action: string } | null | undefined,
  projectStatus: string,
): string {
  return latestReview?.action ?? projectStatus;
}

export function formatApprovalStatusForExport(
  latestApproval: { decision: string } | null | undefined,
  projectStatus: string,
): string {
  return latestApproval?.decision ?? projectStatus;
}

type ExtendedExportInput = LocalContentExportInput & {
  suppliers?: Array<Record<string, unknown>>;
  findings?: Array<Record<string, unknown>>;
};

export async function buildSupplierRegisterPDF(
  input: ExtendedExportInput,
): Promise<LocalContentExportResult> {
  return buildAssessmentSummaryPDF({
    ...input,
    disclaimer: `${input.disclaimer}\nSupplier register rows: ${input.suppliers?.length ?? 0}`,
  });
}

export async function buildGapRiskPDF(
  input: ExtendedExportInput,
): Promise<LocalContentExportResult> {
  return buildAssessmentSummaryPDF({
    ...input,
    disclaimer: `${input.disclaimer}\nFindings rows: ${input.findings?.length ?? 0}`,
  });
}

export async function buildFinalPackagePDF(
  input: ExtendedExportInput,
): Promise<LocalContentExportResult> {
  return buildAssessmentSummaryPDF(input);
}
