// LocalContentOS export service
// PDF and XLSX generation using shared patterns.
// All exports include disclaimer and non-certification statement.

import type { ScoringResult } from "./types";

export interface LocalContentExportInput {
  projectName: string;
  reportingPeriod: string;
  generatedBy: string;
  generatedAt: string;
  reviewStatus: string;
  approvalStatus: string;
  score: ScoringResult;
  disclaimer: string;
}

export interface LocalContentExportResult {
  format: "pdf" | "xlsx";
  filename: string;
  mimeType: string;
  content: string;
}

const DISCLAIMER = [
  "───────────────────────────────────────────",
  "هذا التقرير مُولّد بواسطة LocalContentOS تحت AQLIYA.",
  "يمثل تقييم محتوى محلي محكوم تمت مراجعته واعتماده.",
  "هذا ليس تقرير امتثال نظامي معتمد من جهة تنظيمية.",
  "AI assists. Humans decide. Evidence governs.",
  "───────────────────────────────────────────",
].join("\n");

export function buildAssessmentSummaryPDF(
  input: LocalContentExportInput,
): LocalContentExportResult {
  const lines: string[] = [];

  lines.push("═══════════════════════════════════════════");
  lines.push("LocalContentOS — Local Content Assessment");
  lines.push("═══════════════════════════════════════════");
  lines.push("");
  lines.push(`Project: ${input.projectName}`);
  lines.push(`Reporting Period: ${input.reportingPeriod}`);
  lines.push(`Generated: ${input.generatedAt}`);
  lines.push(`Generated by: ${input.generatedBy}`);
  lines.push(`Review Status: ${input.reviewStatus || "Pending"}`);
  lines.push(`Approval Status: ${input.approvalStatus || "Pending"}`);
  lines.push("");
  lines.push("─── Score Summary ───");
  lines.push(`Total Spend: SAR ${input.score.totalSpend.toLocaleString()}`);
  lines.push(
    `Local Content Percentage: ${input.score.localContentPercentage.toFixed(1)}%`,
  );
  lines.push(`Local Spend: SAR ${input.score.localSpend.toLocaleString()}`);
  lines.push(
    `Non-Local Spend: SAR ${input.score.nonLocalSpend.toLocaleString()}`,
  );
  lines.push("");
  lines.push("─── Suppliers ───");
  lines.push(`Total: ${input.score.supplierCounts.total}`);
  lines.push(`Local: ${input.score.supplierCounts.local}`);
  lines.push(`Non-Local: ${input.score.supplierCounts.nonLocal}`);
  lines.push(`Mixed: ${input.score.supplierCounts.mixed}`);
  lines.push(`Unclassified: ${input.score.supplierCounts.unclassified}`);
  lines.push("");
  lines.push("─── Evidence ───");
  lines.push(`Total: ${input.score.evidenceStats.total}`);
  lines.push(`Verified: ${input.score.evidenceStats.verified}`);
  lines.push(
    `Coverage: ${input.score.evidenceStats.coveragePercentage.toFixed(0)}%`,
  );
  lines.push("");
  lines.push("─── Findings ───");
  lines.push(`Total: ${input.score.findingStats.total}`);
  for (const [severity, count] of Object.entries(
    input.score.findingStats.bySeverity,
  )) {
    lines.push(`  ${severity}: ${count}`);
  }
  lines.push("");
  lines.push(DISCLAIMER);
  lines.push("");
  lines.push("Generated by AQLIYA LocalContentOS v0.1");
  lines.push("═══════════════════════════════════════════");

  return {
    format: "pdf",
    filename: `local_content_assessment_${input.reportingPeriod.replace(/\s+/g, "_")}.txt`,
    mimeType: "text/plain; charset=utf-8",
    content: lines.join("\n"),
  };
}

export function buildSpendClassificationXLSX(
  input: LocalContentExportInput,
): LocalContentExportResult {
  const rows: string[][] = [];

  rows.push(["Category", "Supplier", "Amount (SAR)", "Local %", "Locality"]);
  rows.push(["─── Score Summary ───", "", "", "", ""]);
  rows.push(["Total Spend", "", `${input.score.totalSpend}`, "", ""]);
  rows.push([
    "Local Content %",
    "",
    `${input.score.localContentPercentage.toFixed(1)}`,
    "",
    "",
  ]);
  rows.push(["Local Spend", "", `${input.score.localSpend}`, "", ""]);
  rows.push(["Non-Local Spend", "", `${input.score.nonLocalSpend}`, "", ""]);
  rows.push([""]);
  rows.push(["─── Evidence Coverage ───", "", "", "", ""]);
  rows.push([
    "Coverage",
    "",
    `${input.score.evidenceStats.coveragePercentage.toFixed(0)}%`,
    "",
    "",
  ]);
  rows.push(["Verified", "", `${input.score.evidenceStats.verified}`, "", ""]);
  rows.push(["Total", "", `${input.score.evidenceStats.total}`, "", ""]);
  rows.push([""]);
  rows.push([input.disclaimer]);

  const csvContent = rows
    .map((r) => r.map((c) => `"${c}"`).join(","))
    .join("\n");

  return {
    format: "xlsx",
    filename: `spend_classification_${input.reportingPeriod.replace(/\s+/g, "_")}.csv`,
    mimeType: "text/csv; charset=utf-8",
    content: csvContent,
  };
}

export function buildEvidenceIndexXLSX(
  input: LocalContentExportInput,
): LocalContentExportResult {
  const rows: string[][] = [];
  rows.push(["Evidence Type", "Status", "Count"]);
  rows.push(["Verified", "", `${input.score.evidenceStats.verified}`]);
  rows.push(["Reviewed", "", `${input.score.evidenceStats.reviewed}`]);
  rows.push(["Uploaded", "", `${input.score.evidenceStats.uploaded}`]);
  rows.push(["Linked", "", `${input.score.evidenceStats.linked}`]);
  rows.push(["Rejected", "", `${input.score.evidenceStats.rejected}`]);
  rows.push(["Missing", "", `${input.score.evidenceStats.missing}`]);
  rows.push(["Total", "", `${input.score.evidenceStats.total}`]);
  rows.push([""]);
  rows.push([input.disclaimer]);

  const csvContent = rows
    .map((r) => r.map((c) => `"${c}"`).join(","))
    .join("\n");

  return {
    format: "xlsx",
    filename: `evidence_index_${input.reportingPeriod.replace(/\s+/g, "_")}.csv`,
    mimeType: "text/csv; charset=utf-8",
    content: csvContent,
  };
}
