import type { MetadataRoute } from "next";

const baseUrl = "https://aqliya.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const staticPages = [
    { path: "", changeFreq: "monthly" as const, priority: 1.0 },
    { path: "/platform", changeFreq: "monthly" as const, priority: 0.95 },
    { path: "/industries", changeFreq: "monthly" as const, priority: 0.9 },
    { path: "/proof", changeFreq: "monthly" as const, priority: 0.9 },
    { path: "/governance", changeFreq: "monthly" as const, priority: 0.85 },
    { path: "/about", changeFreq: "monthly" as const, priority: 0.8 },
    { path: "/products", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/products/audit", changeFreq: "monthly" as const, priority: 0.8 },
    {
      path: "/products/decision",
      changeFreq: "monthly" as const,
      priority: 0.7,
    },
    {
      path: "/products/local-content",
      changeFreq: "monthly" as const,
      priority: 0.7,
    },
    { path: "/products/sales", changeFreq: "monthly" as const, priority: 0.7 },
    {
      path: "/products/simulation",
      changeFreq: "monthly" as const,
      priority: 0.7,
    },
    { path: "/how-we-work", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/procurement-pack", changeFreq: "monthly" as const, priority: 0.85 },
    { path: "/print/executive-brief", changeFreq: "monthly" as const, priority: 0.5 },
    { path: "/print/executive-brief-en", changeFreq: "monthly" as const, priority: 0.5 },
    { path: "/print/security-summary", changeFreq: "monthly" as const, priority: 0.5 },
    { path: "/print/data-residency", changeFreq: "monthly" as const, priority: 0.45 },
    { path: "/print/subprocessors", changeFreq: "monthly" as const, priority: 0.45 },
    { path: "/print/dpa-summary", changeFreq: "monthly" as const, priority: 0.45 },
    { path: "/print/pilot-sow-template", changeFreq: "monthly" as const, priority: 0.45 },
    { path: "/print/industry-audit-firms", changeFreq: "monthly" as const, priority: 0.5 },
    { path: "/en", changeFreq: "monthly" as const, priority: 0.85 },
    { path: "/en/executive-brief", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/en/security", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/en/products/audit", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/en/demo", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/en/contact", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/soc2-roadmap", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/pilot-outcomes", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/print/pilot-weekly-metrics", changeFreq: "monthly" as const, priority: 0.4 },
    { path: "/en/soc2-roadmap", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/en/platform", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/en/proof", changeFreq: "monthly" as const, priority: 0.75 },
    { path: "/print/comparison-excel-aqliya", changeFreq: "monthly" as const, priority: 0.4 },
    { path: "/print/objection-handling", changeFreq: "monthly" as const, priority: 0.4 },
    { path: "/print/reference-case-template", changeFreq: "monthly" as const, priority: 0.4 },
    { path: "/contact", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/security", changeFreq: "monthly" as const, priority: 0.8 },
    { path: "/deployment", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/demo", changeFreq: "monthly" as const, priority: 0.8 },
    { path: "/executive-brief", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/pilot-proof", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/proof-library", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/engagement-models", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/case-studies", changeFreq: "monthly" as const, priority: 0.7 },
    { path: "/custom-product", changeFreq: "monthly" as const, priority: 0.6 },
    { path: "/auditos", changeFreq: "monthly" as const, priority: 0.8 },
    {
      path: "/auditos/trial-balance",
      changeFreq: "monthly" as const,
      priority: 0.5,
    },
    { path: "/auditos/mapping", changeFreq: "monthly" as const, priority: 0.5 },
    {
      path: "/auditos/statements",
      changeFreq: "monthly" as const,
      priority: 0.5,
    },
    {
      path: "/auditos/evidence",
      changeFreq: "monthly" as const,
      priority: 0.5,
    },
    {
      path: "/auditos/traceability",
      changeFreq: "monthly" as const,
      priority: 0.5,
    },
  ];

  return staticPages.map(({ path, changeFreq, priority }) => ({
    url: `${baseUrl}${path}`,
    lastModified: new Date(),
    changeFrequency: changeFreq,
    priority,
  }));
}
