// @ts-nocheck — pilot seed overlay; types drift from domain until v0.2 seed sync
// ─── SalesOS seed data (in-memory, no schema migration) ───

import type {
  SalesAccount,
  SalesActivity,
  SalesCompetitorMention,
  SalesContact,
  SalesICPInsight,
  SalesMeeting,
  SalesNextAction,
  SalesObjection,
  SalesOpportunity,
  SalesOutreach,
  SalesProofAsset,
  SalesSignal,
  SalesInteractionLog,
  SalesWinLossInsight,
} from "./types";
import { draftAIConfidence } from "./entity-factory";
import { interactionToActivity } from "./types";

const NOW = new Date().toISOString();
const SEED = { source: "seed" as const };

/** Tier A + Intelligence Core seed volumes (Agent 4 — demo / overlay authority). */
export const TIER_A_SEED_ENTITY_COUNTS = {
  signals: 12,
  objections: 10,
  competitorMentions: 8,
  proofAssets: 9,
  icpInsights: 8,
  nextActions: 10,
  winLossInsights: 4,
  outreach: 6,
  meetings: 8,
  activities: 20,
} as const;

export function buildSalesSeedData(organizationId: string, ownerId: string) {
  const accounts: SalesAccount[] = [
    {
      id: "sales-acct-001",
      organizationId,
      name: "Acme Corp",
      nameAr: "شركة أكمي",
      status: "qualified",
      industry: "Technology",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-acct-002",
      organizationId,
      name: "Global Finance",
      nameAr: "المالية العالمية",
      status: "active",
      industry: "Financial Services",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-acct-003",
      organizationId,
      name: "DataFlow Ltd",
      nameAr: "داتافلو",
      status: "prospect",
      industry: "Data Analytics",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-acct-004",
      organizationId,
      name: "National Energy Co",
      nameAr: "الطاقة الوطنية",
      status: "qualified",
      industry: "Energy",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-acct-005",
      organizationId,
      name: "Riyadh Digital Authority",
      nameAr: "هيئة الرياض الرقمية",
      status: "prospect",
      industry: "Government",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
  ];

  const contacts: SalesContact[] = [
    {
      id: "sales-contact-001",
      accountId: "sales-acct-001",
      organizationId,
      name: "Ahmed Al-Rashid",
      title: "CFO",
      email: "ahmed@acme.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      ...SEED,
    },
    {
      id: "sales-contact-002",
      accountId: "sales-acct-002",
      organizationId,
      name: "Sarah K.",
      title: "VP Procurement",
      email: "sarah@globalfinance.example",
      sensitivityLevel: "restricted",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-003",
      accountId: "sales-acct-001",
      organizationId,
      name: "Layla M.",
      title: "Head of Compliance",
      email: "layla@acme.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-004",
      accountId: "sales-acct-002",
      organizationId,
      name: "Omar H.",
      title: "CIO",
      email: "omar@globalfinance.example",
      sensitivityLevel: "confidential",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-005",
      accountId: "sales-acct-003",
      organizationId,
      name: "Noura S.",
      title: "Data Director",
      email: "noura@dataflow.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-006",
      accountId: "sales-acct-004",
      organizationId,
      name: "Faisal A.",
      title: "Procurement Lead",
      email: "faisal@nec.example",
      sensitivityLevel: "restricted",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-007",
      accountId: "sales-acct-004",
      organizationId,
      name: "Hana T.",
      title: "VP Operations",
      email: "hana@nec.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-008",
      accountId: "sales-acct-005",
      organizationId,
      name: "Yousef R.",
      title: "Program Director",
      email: "yousef@rda.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-009",
      accountId: "sales-acct-005",
      organizationId,
      name: "Maha Q.",
      title: "Governance Lead",
      email: "maha@rda.example",
      sensitivityLevel: "restricted",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
    {
      id: "sales-contact-010",
      accountId: "sales-acct-001",
      organizationId,
      name: "Khalid B.",
      title: "IT Manager",
      email: "khalid@acme.example",
      sensitivityLevel: "standard",
      ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      ...SEED,
    },
  ];

  const opportunities: SalesOpportunity[] = [
    {
      id: "sales-opp-001",
      organizationId,
      accountId: "sales-acct-001",
      name: "AuditOS Enterprise License",
      stage: "Qualification",
      valueEstimate: 480000,
      currency: "SAR",
      qualificationScore: 72,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-002",
      organizationId,
      accountId: "sales-acct-002",
      name: "Institutional Suite Pilot",
      stage: "InReview",
      valueEstimate: 720000,
      currency: "SAR",
      qualificationScore: 85,
      ownerId,
      createdById: ownerId,
      reviewStatus: "InReview",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-003",
      organizationId,
      accountId: "sales-acct-003",
      name: "LocalContentOS Assessment",
      stage: "Draft",
      valueEstimate: 250000,
      currency: "SAR",
      qualificationScore: 55,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-004",
      organizationId,
      accountId: "sales-acct-001",
      name: "WorkflowOS Expansion",
      stage: "Discovery",
      valueEstimate: 320000,
      currency: "SAR",
      qualificationScore: 68,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-005",
      organizationId,
      accountId: "sales-acct-004",
      name: "AuditOS Pilot — NEC",
      stage: "Pilot",
      valueEstimate: 180000,
      currency: "SAR",
      qualificationScore: 78,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-006",
      organizationId,
      accountId: "sales-acct-005",
      name: "DecisionOS Gov Bundle",
      stage: "Proposal",
      valueEstimate: 950000,
      currency: "SAR",
      qualificationScore: 82,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
    {
      id: "sales-opp-007",
      organizationId,
      accountId: "sales-acct-002",
      name: "Platform Renewal 2026",
      stage: "Negotiation",
      valueEstimate: 540000,
      currency: "SAR",
      qualificationScore: 90,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Approved",
      approvalStatus: "Approved",
      ...SEED,
    },
    {
      id: "sales-opp-008",
      organizationId,
      accountId: "sales-acct-003",
      name: "Analytics Add-on",
      stage: "Closed Lost",
      valueEstimate: 120000,
      currency: "SAR",
      qualificationScore: 40,
      ownerId,
      createdById: ownerId,
      reviewStatus: "Draft",
      approvalStatus: "Draft",
      ...SEED,
    },
  ];

  const interactionSummaries: Array<{
    id: string;
    accountId: string;
    opportunityId?: string;
    contactId?: string;
    type: SalesInteractionLog["type"];
    summary: string;
    evidenceRef?: string;
  }> = [
    {
      id: "sales-int-001",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-001",
      contactId: "sales-contact-001",
      type: "meeting",
      summary: "Discovery call — governance requirements discussed",
    },
    {
      id: "sales-int-002",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-002",
      contactId: "sales-contact-002",
      type: "email",
      summary: "Proposal sent — awaiting review",
      evidenceRef: "proposal:draft-002",
    },
    {
      id: "sales-int-003",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-001",
      contactId: "sales-contact-003",
      type: "call",
      summary: "Follow-up on evidence pack",
    },
    {
      id: "sales-int-004",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-007",
      contactId: "sales-contact-004",
      type: "meeting",
      summary: "Renewal terms workshop",
    },
    {
      id: "sales-int-005",
      accountId: "sales-acct-003",
      opportunityId: "sales-opp-003",
      contactId: "sales-contact-005",
      type: "note",
      summary: "ICP fit review — pending data",
    },
    {
      id: "sales-int-006",
      accountId: "sales-acct-004",
      opportunityId: "sales-opp-005",
      contactId: "sales-contact-006",
      type: "meeting",
      summary: "Pilot kickoff scheduled",
    },
    {
      id: "sales-int-007",
      accountId: "sales-acct-005",
      opportunityId: "sales-opp-006",
      contactId: "sales-contact-008",
      type: "meeting",
      summary: "RFP scope alignment",
    },
    {
      id: "sales-int-008",
      accountId: "sales-acct-005",
      opportunityId: "sales-opp-006",
      contactId: "sales-contact-009",
      type: "email",
      summary: "Security questionnaire sent",
    },
    {
      id: "sales-int-009",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-004",
      contactId: "sales-contact-010",
      type: "call",
      summary: "Workflow stakeholders identified",
    },
    {
      id: "sales-int-010",
      accountId: "sales-acct-004",
      opportunityId: "sales-opp-005",
      contactId: "sales-contact-007",
      type: "note",
      summary: "Pilot success criteria drafted",
    },
    {
      id: "sales-int-011",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-002",
      type: "meeting",
      summary: "Commercial review prep",
    },
    {
      id: "sales-int-012",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-001",
      type: "email",
      summary: "Shared qualification template",
    },
    {
      id: "sales-int-013",
      accountId: "sales-acct-003",
      opportunityId: "sales-opp-008",
      type: "call",
      summary: "Loss debrief — budget frozen",
    },
    {
      id: "sales-int-014",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-007",
      type: "email",
      summary: "Contract redlines received",
    },
    {
      id: "sales-int-015",
      accountId: "sales-acct-004",
      opportunityId: "sales-opp-005",
      type: "meeting",
      summary: "Week 2 pilot checkpoint",
    },
    {
      id: "sales-int-016",
      accountId: "sales-acct-005",
      opportunityId: "sales-opp-006",
      type: "note",
      summary: "Competitive landscape noted",
    },
    {
      id: "sales-int-017",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-004",
      type: "meeting",
      summary: "Process mapping session",
    },
    {
      id: "sales-int-018",
      accountId: "sales-acct-003",
      opportunityId: "sales-opp-003",
      type: "call",
      summary: "Intro outreach — no response yet",
    },
    {
      id: "sales-int-019",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-002",
      type: "note",
      summary: "Approver identified — CFO",
    },
    {
      id: "sales-int-020",
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-001",
      contactId: "sales-contact-001",
      type: "meeting",
      summary: "Executive sponsor intro",
    },
  ];

  const interactions: SalesInteractionLog[] = interactionSummaries.map(
    (row) => ({
      organizationId,
      loggedById: ownerId,
      loggedAt: NOW,
      ...row,
    }),
  );

  const activities: SalesActivity[] = interactions.map((i) =>
    interactionToActivity(i, ownerId),
  );
  for (const a of activities) {
    a.source = "seed";
  }

  const objections: SalesObjection[] = [
    {
      id: "sales-obj-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      category: "budget",
      description: "CFO wants ROI proof before pilot",
      resolved: false,
      evidenceRef: "sales-int-003",
    },
    {
      id: "sales-obj-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-002",
      accountId: "sales-acct-002",
      category: "timing",
      description: "Procurement cycle delayed to Q3",
      resolved: false,
      evidenceRef: "sales-int-011",
    },
    {
      id: "sales-obj-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      category: "security",
      description: "Data residency concerns raised",
      resolved: false,
      confidence: draftAIConfidence(0.72),
      evidenceRef: "sales-int-008",
    },
    {
      id: "sales-obj-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      category: "implementation",
      description: "Pilot scope must include Arabic UI",
      resolved: false,
      evidenceRef: "sales-int-010",
    },
    {
      id: "sales-obj-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-007",
      accountId: "sales-acct-002",
      category: "pricing",
      description: "Renewal discount capped at 8%",
      frequency: 2,
      resolved: false,
      evidenceRef: "sales-int-014",
    },
    {
      id: "sales-obj-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-004",
      accountId: "sales-acct-001",
      category: "change_management",
      description: "Workflow adoption risk across subsidiaries",
      resolved: false,
      confidence: draftAIConfidence(0.65),
      evidenceRef: "sales-int-017",
    },
    {
      id: "sales-obj-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      category: "procurement",
      description: "RFP requires three reference accounts in government sector",
      resolved: false,
      evidenceRef: "sales-int-007",
    },
    {
      id: "sales-obj-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-003",
      accountId: "sales-acct-003",
      category: "timing",
      description: "Assessment paused until data platform RFP closes",
      resolved: false,
      confidence: draftAIConfidence(0.69),
      evidenceRef: "sales-int-018",
    },
    {
      id: "sales-obj-009",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-002",
      accountId: "sales-acct-002",
      category: "integration",
      description: "Must integrate with existing ERP audit module",
      frequency: 1,
      resolved: false,
      evidenceRef: "sales-int-019",
    },
    {
      id: "sales-obj-010",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      category: "budget",
      description: "Full rollout contingent on pilot KPI threshold",
      resolved: false,
      confidence: draftAIConfidence(0.77),
      evidenceRef: "sales-int-015",
    },
  ];

  const signals: SalesSignal[] = [
    {
      id: "sales-sig-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-007",
      signalType: "timing",
      description: "Renewal intent confirmed by VP",
      strength: "strong",
      confidence: draftAIConfidence(0.91),
      evidenceRef: "sales-int-004",
    },
    {
      id: "sales-sig-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-008",
      accountId: "sales-acct-003",
      signalType: "budget",
      description: "Budget freeze signal",
      strength: "strong",
      confidence: draftAIConfidence(0.87),
      evidenceRef: "sales-int-013",
    },
    {
      id: "sales-sig-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      signalType: "authority",
      description: "Program director named economic buyer",
      strength: "moderate",
      confidence: draftAIConfidence(0.79),
      evidenceRef: "sales-int-007",
    },
    {
      id: "sales-sig-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      signalType: "need",
      description: "Pilot success criteria aligned to audit KPIs",
      strength: "strong",
      evidenceRef: "sales-int-015",
    },
    {
      id: "sales-sig-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      signalType: "buying",
      description: "Executive sponsor engaged for enterprise license",
      strength: "moderate",
      confidence: draftAIConfidence(0.74),
      evidenceRef: "sales-int-020",
    },
    {
      id: "sales-sig-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-002",
      accountId: "sales-acct-002",
      signalType: "timing",
      description: "Commercial review window opens next month",
      strength: "moderate",
      confidence: draftAIConfidence(0.7),
      evidenceRef: "sales-int-011",
    },
    {
      id: "sales-sig-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-004",
      accountId: "sales-acct-001",
      signalType: "other",
      description: "Subsidiary rollout may require phased licensing",
      strength: "weak",
      confidence: draftAIConfidence(0.58),
      evidenceRef: "sales-int-017",
    },
    {
      id: "sales-sig-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-003",
      accountId: "sales-acct-003",
      signalType: "need",
      description: "Local content compliance gap cited in intro note",
      strength: "moderate",
      evidenceRef: "sales-int-005",
    },
    {
      id: "sales-sig-009",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      signalType: "budget",
      description: "CFO requested phased payment option",
      strength: "moderate",
      confidence: draftAIConfidence(0.69),
      evidenceRef: "sales-obj-001",
    },
    {
      id: "sales-sig-010",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      signalType: "budget",
      description: "RFP budget band published — within DecisionOS bundle range",
      strength: "strong",
      confidence: draftAIConfidence(0.83),
      evidenceRef: "sales-int-016",
    },
    {
      id: "sales-sig-011",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      signalType: "need",
      description: "Operations VP aligned on audit KPI baseline",
      strength: "strong",
      evidenceRef: "sales-int-010",
    },
    {
      id: "sales-sig-012",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      signalType: "need",
      description: "Compliance lead requested Arabic evidence pack",
      strength: "moderate",
      confidence: draftAIConfidence(0.75),
      evidenceRef: "sales-int-003",
    },
  ];

  const competitorMentions: SalesCompetitorMention[] = [
    {
      id: "sales-comp-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      competitorName: "Legacy GRC Suite",
      context: "Incumbent named in RFP",
      threatLevel: "medium",
      evidenceRef: "sales-int-016",
    },
    {
      id: "sales-comp-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      competitorName: "Spreadsheet workflow",
      context: "Status quo alternative",
      threatLevel: "low",
      evidenceRef: "sales-int-001",
    },
    {
      id: "sales-comp-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-002",
      accountId: "sales-acct-002",
      competitorName: "Regional ERP add-on",
      context: "Bundled with existing ERP contract",
      threatLevel: "high",
      evidenceRef: "sales-int-002",
    },
    {
      id: "sales-comp-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-008",
      accountId: "sales-acct-003",
      competitorName: "Build vs buy",
      context: "Internal analytics team preferred",
      threatLevel: "medium",
      confidence: draftAIConfidence(0.68),
      evidenceRef: "sales-int-013",
    },
    {
      id: "sales-comp-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      competitorName: "Manual audit checklists",
      context: "Incumbent process before pilot",
      threatLevel: "low",
      evidenceRef: "sales-int-006",
    },
    {
      id: "sales-comp-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-004",
      accountId: "sales-acct-001",
      competitorName: "Point workflow tools",
      context: "IT manager evaluating best-of-breed",
      threatLevel: "medium",
      confidence: draftAIConfidence(0.61),
      evidenceRef: "sales-int-009",
    },
    {
      id: "sales-comp-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-007",
      accountId: "sales-acct-002",
      competitorName: "In-house renewal team",
      context: "Internal build proposed for renewal analytics",
      threatLevel: "low",
      evidenceRef: "sales-int-014",
    },
    {
      id: "sales-comp-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-003",
      accountId: "sales-acct-003",
      competitorName: "Global content platform",
      context: "Incumbent for local content reporting",
      threatLevel: "high",
      evidenceRef: "sales-int-005",
    },
  ];

  const proofAssets: SalesProofAsset[] = [
    {
      id: "sales-proof-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "case_study",
      title: "Financial sector AuditOS pilot summary",
      accountId: "sales-acct-001",
      linkedAccountIds: ["sales-acct-001"],
      linkedOpportunityIds: ["sales-opp-001"],
      externalRef: "proof:auditos-fin-01",
      evidenceRef: "sales-int-001",
    },
    {
      id: "sales-proof-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "customer_quote",
      title: "Energy sector reference call",
      accountId: "sales-acct-004",
      opportunityId: "sales-opp-005",
      linkedOpportunityIds: ["sales-opp-005"],
      externalRef: "proof:ref-nec-01",
      evidenceRef: "sales-int-006",
    },
    {
      id: "sales-proof-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "proposal",
      title: "Institutional Suite pilot proposal",
      linkedOpportunityIds: ["sales-opp-002"],
      externalRef: "proof:proposal-002",
      evidenceRef: "sales-int-002",
    },
    {
      id: "sales-proof-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "pilot_result",
      title: "NEC week-2 pilot checkpoint metrics",
      linkedAccountIds: ["sales-acct-004"],
      linkedOpportunityIds: ["sales-opp-005"],
      externalRef: "proof:pilot-nec-w2",
      evidenceRef: "sales-int-015",
    },
    {
      id: "sales-proof-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      assetType: "objection_response",
      title: "Data residency FAQ pack",
      linkedOpportunityIds: ["sales-opp-006"],
      externalRef: "proof:security-faq-gov",
      evidenceRef: "sales-int-008",
      confidence: draftAIConfidence(0.76),
    },
    {
      id: "sales-proof-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "benchmark",
      title: "Enterprise license ROI benchmark — technology sector",
      linkedOpportunityIds: ["sales-opp-001"],
      linkedAccountIds: ["sales-acct-001"],
      externalRef: "proof:roi-tech-benchmark",
      evidenceRef: "sales-int-012",
    },
    {
      id: "sales-proof-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "demo_recording",
      title: "WorkflowOS process mapping demo",
      linkedOpportunityIds: ["sales-opp-004"],
      externalRef: "proof:workflow-demo-01",
      evidenceRef: "sales-int-017",
    },
    {
      id: "sales-proof-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      assetType: "audit_evidence",
      title: "Gov sector security attestation pack",
      linkedOpportunityIds: ["sales-opp-006"],
      externalRef: "proof:gov-attestation-01",
      evidenceRef: "sales-int-008",
      confidence: draftAIConfidence(0.8),
    },
    {
      id: "sales-proof-009",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      assetType: "customer_quote",
      title: "Global Finance renewal reference",
      linkedOpportunityIds: ["sales-opp-007"],
      linkedAccountIds: ["sales-acct-002"],
      externalRef: "proof:gf-renewal-ref",
      evidenceRef: "sales-int-004",
    },
  ];

  const icpInsights: SalesICPInsight[] = [
    {
      id: "sales-icp-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-002",
      dimension: "industry",
      hypothesis:
        "Financial services accounts show strong close rates with STANDARD pricing",
      evidenceSummary: "Active account, high qualification scores",
      confidence: draftAIConfidence(0.88),
      evidenceRef: "sales-int-004",
    },
    {
      id: "sales-icp-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-005",
      dimension: "region",
      hypothesis:
        "Government bundle opportunities need extended security review",
      evidenceSummary: "Proposal stage, large value",
      confidence: draftAIConfidence(0.82),
      evidenceRef: "sales-int-007",
    },
    {
      id: "sales-icp-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      dimension: "company_size",
      hypothesis: "Mid-market energy accounts convert on pilot-first motion",
      evidenceSummary: "Pilot stage with defined success criteria",
      confidence: draftAIConfidence(0.8),
      evidenceRef: "sales-int-010",
    },
    {
      id: "sales-icp-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      dimension: "pain_point",
      hypothesis: "Prospects without executive sponsor stall in discovery",
      evidenceSummary: "DataFlow assessment still in Draft",
      confidence: draftAIConfidence(0.71),
      evidenceRef: "sales-int-018",
    },
    {
      id: "sales-icp-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-001",
      dimension: "title",
      hypothesis: "CFO + Head of Compliance pair accelerates enterprise deals",
      evidenceSummary: "Budget objection paired with compliance follow-up",
      recommendation: "Multi-thread CFO and compliance on qualification",
      confidence: draftAIConfidence(0.77),
      evidenceRef: "sales-int-003",
    },
    {
      id: "sales-icp-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-004",
      dimension: "other",
      hypothesis: "Energy sector pilots convert when Arabic UI is in scope",
      evidenceSummary: "Implementation objection resolved via pilot criteria",
      confidence: draftAIConfidence(0.75),
      evidenceRef: "sales-obj-004",
    },
    {
      id: "sales-icp-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-004",
      dimension: "pain_point",
      hypothesis:
        "Energy accounts buy on measurable pilot KPIs not feature lists",
      evidenceSummary: "NEC pilot criteria and week-2 checkpoint",
      confidence: draftAIConfidence(0.86),
      evidenceRef: "sales-int-015",
    },
    {
      id: "sales-icp-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      accountId: "sales-acct-001",
      dimension: "industry",
      hypothesis:
        "Workflow expansion follows audit license when IT sponsors mapped",
      evidenceSummary: "Workflow stakeholders identified post-discovery",
      confidence: draftAIConfidence(0.73),
      evidenceRef: "sales-int-009",
    },
  ];

  const nextActions: SalesNextAction[] = [
    {
      id: "sales-next-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-003",
      accountId: "sales-acct-003",
      title: "Schedule discovery conversation",
      description: "Draft-stage opportunity needs first activity",
      priority: "high",
      ruleId: "new_no_activity",
      recommendationOnly: true,
    },
    {
      id: "sales-next-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      title: "Attach ROI case study to objection thread",
      description: "Budget objection unresolved",
      priority: "urgent",
      ruleId: "objection_unresolved",
      recommendationOnly: true,
      evidenceRef: "sales-obj-001",
    },
    {
      id: "sales-next-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      title: "Complete security questionnaire follow-up",
      priority: "high",
      ruleId: "gov_security_review",
      recommendationOnly: true,
      evidenceRef: "sales-int-008",
    },
    {
      id: "sales-next-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-007",
      accountId: "sales-acct-002",
      title: "Finalize renewal redlines",
      priority: "medium",
      ruleId: "negotiation_active",
      recommendationOnly: true,
      evidenceRef: "sales-int-014",
    },
    {
      id: "sales-next-005",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      title: "Publish pilot week-2 readout",
      priority: "medium",
      ruleId: "pilot_checkpoint",
      recommendationOnly: true,
      evidenceRef: "sales-int-015",
    },
    {
      id: "sales-next-006",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-004",
      accountId: "sales-acct-001",
      title: "Share subsidiary workflow demo recording",
      description: "IT stakeholders identified; proof asset ready",
      priority: "high",
      ruleId: "stakeholder_engagement",
      recommendationOnly: true,
      evidenceRef: "sales-proof-007",
    },
    {
      id: "sales-next-007",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-002",
      accountId: "sales-acct-002",
      title: "Confirm ERP integration scope with CIO",
      priority: "high",
      ruleId: "integration_clarification",
      recommendationOnly: true,
      evidenceRef: "sales-obj-009",
    },
    {
      id: "sales-next-008",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-006",
      accountId: "sales-acct-005",
      title: "Submit government reference accounts",
      priority: "high",
      ruleId: "rfp_reference_gate",
      recommendationOnly: true,
      evidenceRef: "sales-obj-007",
    },
    {
      id: "sales-next-009",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-001",
      accountId: "sales-acct-001",
      title: "Deliver Arabic compliance evidence pack",
      priority: "medium",
      ruleId: "compliance_evidence",
      recommendationOnly: true,
      evidenceRef: "sales-sig-012",
    },
    {
      id: "sales-next-010",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-008",
      accountId: "sales-acct-003",
      title: "Capture loss learnings for ICP model",
      priority: "low",
      ruleId: "closed_lost_debrief",
      recommendationOnly: true,
      evidenceRef: "sales-wl-001",
    },
  ];

  const winLossInsights: SalesWinLossInsight[] = [
    {
      id: "sales-wl-001",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-008",
      accountId: "sales-acct-003",
      outcome: "lost",
      primaryReason: "budget_freeze",
      contributingFactors: ["timing", "no_executive_sponsor"],
      competitorInvolved: "Build vs buy",
      evidenceRef: "sales-int-013",
    },
    {
      id: "sales-wl-002",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-007",
      accountId: "sales-acct-002",
      outcome: "won",
      primaryReason: "expansion_fit",
      contributingFactors: ["strong_renewal_signal", "approved_pricing"],
      confidence: draftAIConfidence(0.84),
      evidenceRef: "sales-int-014",
    },
    {
      id: "sales-wl-003",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "draft",
      source: "ai_draft",
      opportunityId: "sales-opp-005",
      accountId: "sales-acct-004",
      outcome: "won",
      primaryReason: "pilot_success",
      contributingFactors: ["aligned_kpis", "reference_call"],
      competitorInvolved: "Manual audit checklists",
      confidence: draftAIConfidence(0.79),
      evidenceRef: "sales-int-015",
    },
    {
      id: "sales-wl-004",
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "manual",
      opportunityId: "sales-opp-003",
      accountId: "sales-acct-003",
      outcome: "lost",
      primaryReason: "no_engagement",
      contributingFactors: ["timing", "incumbent_platform"],
      competitorInvolved: "Global content platform",
      evidenceRef: "sales-int-018",
    },
  ];

  const outreach: SalesOutreach[] = [
    {
      id: "sales-out-001",
      organizationId,
      accountId: "sales-acct-003",
      opportunityId: "sales-opp-003",
      contactId: "sales-contact-005",
      channel: "email",
      messageSummary: "Intro outreach — LocalContentOS assessment",
      sentAt: NOW,
      responseReceived: false,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
    {
      id: "sales-out-002",
      organizationId,
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-002",
      contactId: "sales-contact-002",
      channel: "linkedin",
      messageSummary: "Pilot follow-up — institutional suite",
      sentAt: NOW,
      responseReceived: true,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
    {
      id: "sales-out-003",
      organizationId,
      accountId: "sales-acct-005",
      opportunityId: "sales-opp-006",
      contactId: "sales-contact-008",
      channel: "email",
      messageSummary: "RFP clarifications — DecisionOS bundle",
      sentAt: NOW,
      responseReceived: false,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
    {
      id: "sales-out-004",
      organizationId,
      accountId: "sales-acct-001",
      opportunityId: "sales-opp-001",
      contactId: "sales-contact-001",
      channel: "email",
      messageSummary: "ROI benchmark + case study — AuditOS enterprise",
      sentAt: NOW,
      responseReceived: true,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
    {
      id: "sales-out-005",
      organizationId,
      accountId: "sales-acct-004",
      opportunityId: "sales-opp-005",
      contactId: "sales-contact-007",
      channel: "call",
      messageSummary: "Pilot week-2 readout invitation",
      sentAt: NOW,
      responseReceived: false,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
    {
      id: "sales-out-006",
      organizationId,
      accountId: "sales-acct-002",
      opportunityId: "sales-opp-007",
      contactId: "sales-contact-004",
      channel: "email",
      messageSummary: "Renewal redline summary — legal review",
      sentAt: NOW,
      responseReceived: true,
      loggedById: ownerId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active",
      source: "seed",
    },
  ];

  const meetingActionItems: Record<string, string[]> = {
    "sales-int-001": [
      "Send governance requirements checklist",
      "Book compliance workshop with Layla",
    ],
    "sales-int-006": [
      "Confirm pilot Arabic UI scope",
      "Share week-1 metrics template",
    ],
    "sales-int-007": [
      "Align RFP annex to DecisionOS modules",
      "Identify reference accounts",
    ],
    "sales-int-015": ["Publish KPI readout deck", "Schedule executive readout"],
    "sales-int-017": [
      "Map subsidiary workflow owners",
      "Draft rollout wave plan",
    ],
    "sales-int-020": [
      "Intro deck for executive sponsor",
      "Confirm budget committee date",
    ],
  };

  const meetings: SalesMeeting[] = interactions
    .filter((i) => i.type === "meeting")
    .map((i) => ({
      id: `meet-${i.id}`,
      organizationId,
      createdById: ownerId,
      createdAt: NOW,
      updatedAt: NOW,
      status: "active" as const,
      source: "seed" as const,
      accountId: i.accountId,
      opportunityId: i.opportunityId,
      contactId: i.contactId,
      scheduledAt: i.loggedAt,
      summary: i.summary,
      actionItems: meetingActionItems[i.id],
      hasSummary: true,
      loggedById: ownerId,
    }));

  return {
    accounts,
    contacts,
    opportunities,
    interactions,
    activities,
    meetings,
    outreach,
    objections,
    signals,
    competitorMentions,
    proofAssets,
    icpInsights,
    nextActions,
    winLossInsights,
  };
}
