import "server-only";

import { isEnabled } from "@/lib/platform/feature-flags/registry";
import { prisma } from "@/lib/prisma";
import {
  createDisclosureNote,
  getDisclosureNotes,
  updateDisclosureNote,
} from "@/lib/audit/db/index";
import { recordAuditOsAuditEvent } from "@/lib/audit/audit-events";
import {
  isIfrsRulesEnabled,
  isSocpaRulesEnabled,
  runIfrsRulesForEngagement,
  runSocpaRulesForEngagement,
} from "@/lib/audit/rules";
import {
  buildDraftFromTrigger,
  dedupeUnifiedTriggers,
  findMatchingNote,
  mergeMissingInformation,
  mergeTriggerLists,
  nextNoteNumber,
  shouldSkipExistingNote,
  unifyIfrsTriggers,
  unifySocpaTriggers,
} from "./disclosure-engine";
import type { DisclosureAutoRunResult } from "./disclosure-engine-types";

export function isDisclosureAutoEnabled(): boolean {
  return isEnabled("audit.disclosure-auto");
}

export async function runDisclosureAutoForEngagement(
  engagementId: string,
): Promise<DisclosureAutoRunResult> {
  let existingNotes = await getDisclosureNotes(engagementId);

  const ifrsTriggers = isIfrsRulesEnabled()
    ? unifyIfrsTriggers(
        (await runIfrsRulesForEngagement(engagementId)).disclosureTriggers,
      )
    : [];

  let socpaTriggers: ReturnType<typeof unifySocpaTriggers> = [];
  if (isSocpaRulesEnabled()) {
    const socpaResult = await runSocpaRulesForEngagement(engagementId);
    if (socpaResult.jurisdictionApplicable) {
      socpaTriggers = unifySocpaTriggers(socpaResult.disclosureTriggers);
    }
  }

  const collected = mergeTriggerLists(ifrsTriggers, socpaTriggers);
  const triggers = dedupeUnifiedTriggers(collected);

  let notesCreated = 0;
  let notesUpdated = 0;
  let notesSkipped = 0;

  for (const trigger of triggers) {
    const existing = findMatchingNote(existingNotes, trigger);
    if (existing && shouldSkipExistingNote(existing.status)) {
      notesSkipped += 1;
      continue;
    }

    const draft = buildDraftFromTrigger(trigger);

    if (existing) {
      await updateDisclosureNote(existing.id, {
        content: draft.content,
        missingInformation: mergeMissingInformation(
          existing.missingInformation,
          draft.missingInformation,
        ),
        aiDrafted: true,
      });
      notesUpdated += 1;
    } else {
      const noteNumber = nextNoteNumber(existingNotes);
      const created = await createDisclosureNote({
        engagementId,
        noteNumber,
        title: draft.title,
        noteType: draft.noteType,
        content: draft.content,
        missingInformation: draft.missingInformation,
        aiDrafted: true,
      });
      existingNotes = [...existingNotes, created];
      notesCreated += 1;
    }
  }

  const result: DisclosureAutoRunResult = {
    engagementId,
    triggersCollected: collected.length,
    triggersDeduped: triggers.length,
    notesCreated,
    notesUpdated,
    notesSkipped,
    runAt: new Date().toISOString(),
  };

  await recordAuditOsAuditEvent({
    engagementId,
    eventType: "disclosure.auto_completed",
    actorId: "system",
    actorName: "Disclosure Auto Engine",
    actorRole: "system",
    targetType: "disclosure_auto",
    targetId: engagementId,
    description: `Disclosure auto: ${notesCreated} created, ${notesUpdated} updated, ${notesSkipped} skipped`,
    metadata: result as unknown as Record<string, unknown>,
  });

  try {
    const engagement = await prisma.auditEngagement.findUnique({
      where: { id: engagementId },
      select: { organizationId: true },
    });
    const { maybeRunAuditIntelligenceAfterDisclosure } = await import(
      "@/lib/audit/intelligence"
    );
    await maybeRunAuditIntelligenceAfterDisclosure(
      engagementId,
      engagement?.organizationId,
    );
  } catch (intelErr) {
    console.error(
      `[Disclosure Auto] intelligence hook failed for ${engagementId}`,
      intelErr,
    );
  }

  return result;
}

/** Non-blocking hook after SOCPA rules (Phase 8) */
export async function maybeAutoGenerateDisclosureNotes(
  engagementId: string,
  _organizationId?: string,
): Promise<void> {
  if (!isDisclosureAutoEnabled()) return;
  try {
    await runDisclosureAutoForEngagement(engagementId);
  } catch (err) {
    console.error(
      `[Disclosure Auto] post-rules hook failed for ${engagementId}`,
      err,
    );
  }
}
