// AQLIYA AuditOS — Pilot Daily Monitor
// Run: npx tsx scripts/pilot-daily-monitor.ts
// Produces a structured daily pilot status report.

import { config } from "dotenv"
import { resolve } from "path"

config({ path: resolve(__dirname, "../.env") })

import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const OK = "✅"
const FAIL = "❌"
const WARN = "⚠️ "

interface ReportSection {
  title: string
  lines: string[]
}

const report: ReportSection[] = []

function emit(title: string, lines: string[]) {
  report.push({ title, lines })
}

function fmt(name: string, ok: boolean, detail: string) {
  return `  ${ok ? OK : FAIL} ${name}: ${detail}`
}

async function main() {
  const now = new Date()
  emit("PILOT DAILY STATUS REPORT", [
    `  Date: ${now.toISOString().split("T")[0]}`,
    `  Time: ${now.toISOString().split("T")[1].split(".")[0]} UTC`,
    `  Report generated by: pilot-daily-monitor.ts`,
  ])

  let prisma: PrismaClient | null = null
  try {
    const adapter = new PrismaPg(process.env.DATABASE_URL!)
    prisma = new PrismaClient({ adapter })

    // 1. Health Check
    await prisma.$queryRaw`SELECT 1`
    const engCount = await prisma.auditEngagement.count()
    const eventCount = await prisma.auditEvent.count()
    const aiCount = await prisma.auditAiOutput.count()
    const userCount = await prisma.auditUser.count()
    const openBlockers = await prisma.productionBlocker.count({ where: { status: "open" } })
    const healthOk = engCount > 0 && eventCount > 0
    emit("1. HEALTH CHECK", [
      fmt("Database connectivity", true, "Connected"),
      fmt("Engagements", engCount > 0, `${engCount} total`),
      fmt("Audit events", true, `${eventCount} total`),
      fmt("AI outputs", true, `${aiCount} total`),
      fmt("Audit users", userCount > 0, `${userCount} users`),
      fmt("Open blockers", openBlockers === 0, `${openBlockers} open`),
      fmt("OVERALL", healthOk, healthOk ? "All systems operational" : "Issues detected"),
    ])

    // 2. Workflow Status
    const findings = await prisma.auditFinding.count()
    const recs = await prisma.auditRecommendation.count()
    const evidence = await prisma.auditEvidence.count()
    const comments = await prisma.auditReviewComment.count()
    const maps = await prisma.auditAccountMapping.count()
    const pendingMaps = await prisma.auditAccountMapping.count({ where: { status: "pending" } })
    const missingEvidence = await prisma.auditEvidence.count({ where: { state: "missing" } })
    const openComments = await prisma.auditReviewComment.count({ where: { status: "open" } })
    const approved = await prisma.auditApprovalRecord.count({ where: { action: "approved" } })

    emit("2. WORKFLOW STATUS", [
      fmt("Engagements", engCount >= 1, `${engCount} engagement(s)`),
      fmt("Account mappings", maps > 0, `${maps} total, ${pendingMaps} pending`),
      fmt("Evidence items", evidence > 0, `${evidence} items, ${missingEvidence} missing`),
      fmt("Findings", findings > 0, `${findings} total`),
      fmt("Recommendations", recs > 0, `${recs} total`),
      fmt("Review comments", comments > 0, `${comments} total, ${openComments} open`),
      fmt("Approvals", approved > 0, `${approved} approval(s)`),
      fmt("AI outputs", aiCount > 0, `${aiCount} total`),
      fmt("Audit events", eventCount > 0, `${eventCount} events`),
    ])

    // 3. Blocker Status
    const allBlockers = await prisma.productionBlocker.findMany({ orderBy: { createdAt: "asc" } })
    const blockerLines = allBlockers.map(b => `  ${b.status === "resolved" ? OK : b.status === "in_review" || b.status === "in_progress" ? WARN : FAIL} ${b.title.padEnd(45)} ${b.status}`)
    emit("3. PRODUCTION BLOCKERS", blockerLines.length > 0 ? blockerLines : ["  No blockers defined"])

    // 4. Recent Activity
    const recentEvents = await prisma.auditEvent.findMany({
      where: { engagementId: "eng-gulf-2025" },
      orderBy: { timestamp: "desc" },
      take: 5,
    })
    emit("4. RECENT EVENTS (last 5)", recentEvents.map(e =>
      `  ${e.timestamp.toISOString().split("T")[0]} ${e.eventType.padEnd(40)} ${e.actorName}`
    ))

    // 5. Upload & Auth Failure Monitoring
    const uploadErrors = await prisma.auditEvent.count({
      where: { engagementId: "eng-gulf-2025", eventType: { in: ["evidence.file_scanned", "evidence.created"] }, timestamp: { gte: new Date(Date.now() - 86400000) } },
    })
    const uploadRejections = await prisma.auditEvent.count({
      where: { eventType: "evidence.file_scanned", metadata: { path: ["scanStatus"], equals: "error" } },
    })
    const authFailureEvents = await prisma.auditEvent.count({
      where: { eventType: { in: ["engagement.state_changed", "finding.state_changed"] }, description: { contains: "Access denied" } },
    })
    const roleDeniedEvents = await prisma.auditEvent.count({
      where: { description: { contains: "Access denied" } },
    })
    emit("5. UPLOAD & AUTH MONITORING", [
      fmt("Evidence events (24h)", true, `${uploadErrors} events`),
      fmt("Upload rejections", uploadRejections === 0, `${uploadRejections} rejected`),
      fmt("Auth failures (Access denied)", authFailureEvents === 0, `${authFailureEvents} events`),
      fmt("Role denied events", roleDeniedEvents === 0, `${roleDeniedEvents} events`),
      "  Upload + auth failures tracked via AuditEvent trail. Alerts: monitor daily threshold > 0.",
    ])

    // 6. Pilot Feedback
    const feedbackItems = await prisma.pilotFeedback.findMany({ orderBy: { createdAt: "desc" }, take: 10 })
    const openFeedback = feedbackItems.filter(f => f.status === "open").length
    emit("6. PILOT FEEDBACK", [
      fmt("Total feedback", true, `${feedbackItems.length} items`),
      fmt("Open feedback", openFeedback === 0, `${openFeedback} open`),
      ...feedbackItems.slice(0, 5).map(f =>
        `     ${f.status === "open" ? "🟡" : "🟢"} ${f.title.substring(0, 60)} [${f.severity}]`
      ),
    ])

    // 7. Summary
    const allGood = healthOk && openBlockers === 0
    emit("7. SUMMARY", [
      `  Status: ${allGood ? "✅ ALL SYSTEMS OPERATIONAL" : "⚠️  ISSUES DETECTED"}`,
      `  Engagements: ${engCount}`,
      `  Events: ${eventCount}`,
      `  Open Blockers: ${openBlockers}`,
      `  Open Feedback: ${openFeedback}`,
      ``,
      `  Risk Acceptance Form: ⏳ Required before real client data`,
      `  Pilot type: ${openBlockers === 0 ? "Limited production pilot" : "Development/demo"}`,
    ])

  } catch (e: unknown) {
    emit("ERROR", [`  ${FAIL} Monitoring error: ${(e as Error).message}`])
  } finally {
    if (prisma) await prisma.$disconnect()
  }

  // Print report
  console.log("\n" + "=".repeat(60))
  for (const section of report) {
    console.log(`\n${section.title}`)
    console.log("-".repeat(40))
    for (const line of section.lines) {
      console.log(line)
    }
  }
  console.log("\n" + "=".repeat(60))
  console.log("End of pilot daily status report\n")
}

main().catch(e => {
  console.error(`\n${FAIL} Monitor error:`, e.message)
  process.exit(1)
})
