import "server-only";
import PDFDocument from "pdfkit";

export interface ContentStudioExportInput {
  contentId: string;
  title: string;
  body: string;
  summary: string | null;
  status: string;
  contentType: string;
  version: number;
  locale: string;
  tags: string[];
  workspaceName: string;
  createdByName: string | null;
  reviewedByName: string | null;
  approvedByName: string | null;
  publishedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  exportedAt: Date;
}

export interface ContentStudioExportResult {
  format: "pdf";
  filename: string;
  mimeType: string;
  content: Buffer;
}

export async function buildContentStudioPDF(
  input: ContentStudioExportInput,
): Promise<ContentStudioExportResult> {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 40, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `${input.title} — ContentStudio`,
      Author: "AQLIYA ContentStudio",
      Subject: "Content Studio Export",
      Creator: "AQLIYA ContentStudio",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const endPromise = new Promise<void>((resolve) =>
    doc.on("end", () => resolve()),
  );

  const statusLabels: Record<string, string> = {
    DRAFT: "مسودة",
    IN_REVIEW: "قيد المراجعة",
    APPROVED: "معتمد",
    PUBLISHED: "منشور",
    ARCHIVED: "مؤرشف",
  };

  // ─── Header ───
  doc.fontSize(16).font("Helvetica-Bold").text("ContentStudio", {
    align: "center",
  });
  doc
    .fontSize(12)
    .font("Helvetica")
    .text("تقرير المحتوى — Content Report", { align: "center" });
  doc.moveDown(0.5);

  // ─── Meta section ───
  doc.fontSize(8).font("Helvetica");
  doc.text(`تم التصدير: ${input.exportedAt.toISOString()}`);
  doc.text(`المساحة: ${input.workspaceName}`);
  doc.text(`الإصدار: v${input.version}`);
  doc.text(
    `الحالة: ${statusLabels[input.status] || input.status}`,
  );
  doc.text(`النوع: ${input.contentType}`);
  doc.moveDown(0.5);

  // ─── Title ───
  doc.fontSize(14).font("Helvetica-Bold").text(input.title);
  doc.moveDown(0.3);

  // ─── Summary ───
  if (input.summary) {
    doc
      .fontSize(10)
      .font("Helvetica-Oblique")
      .fillColor("#555555")
      .text(input.summary);
    doc.fillColor("#000000");
    doc.moveDown(0.3);
  }

  // ─── Tags ───
  if (input.tags.length > 0) {
    doc.fontSize(8).font("Helvetica").fillColor("#666666");
    doc.text(`الوسوم: ${input.tags.join(" • ")}`);
    doc.fillColor("#000000");
    doc.moveDown(0.3);
  }

  // ─── Body ───
  doc.fontSize(10).font("Helvetica");
  // Split body by lines and render each
  const lines = input.body.split("\n");
  for (const line of lines) {
    // Simple markdown heading detection
    if (line.startsWith("# ")) {
      doc.fontSize(13).font("Helvetica-Bold").text(line.replace(/^# /, ""));
    } else if (line.startsWith("## ")) {
      doc.fontSize(11).font("Helvetica-Bold").text(line.replace(/^## /, ""));
    } else if (line.startsWith("### ")) {
      doc.fontSize(10).font("Helvetica-Bold").text(line.replace(/^### /, ""));
    } else if (line.startsWith("- ")) {
      doc.fontSize(9).font("Helvetica").text(`  •  ${line.slice(2)}`);
    } else if (line.trim() === "") {
      doc.moveDown(0.2);
    } else {
      doc.fontSize(9).font("Helvetica").text(line);
    }
  }
  doc.moveDown(0.5);

  // ─── Metadata footer ───
  doc
    .fontSize(8)
    .font("Helvetica")
    .fillColor("#888888");
  doc.text(`تاريخ الإنشاء: ${input.createdAt.toISOString().split("T")[0]}`);
  doc.text(`آخر تحديث: ${input.updatedAt.toISOString().split("T")[0]}`);
  if (input.createdByName) {
    doc.text(`المنشئ: ${input.createdByName}`);
  }
  if (input.reviewedByName) {
    doc.text(`المراجع: ${input.reviewedByName}`);
  }
  if (input.approvedByName) {
    doc.text(`المعتمد: ${input.approvedByName}`);
  }
  if (input.publishedAt) {
    doc.text(
      `تاريخ النشر: ${input.publishedAt.toISOString().split("T")[0]}`,
    );
  }
  doc.fillColor("#000000");

  // ─── Footer disclaimer ───
  doc.moveDown(1);
  doc
    .fontSize(7)
    .fillColor("#aaaaaa")
    .font("Helvetica")
    .text(
      "هذا التقرير مولّد بواسطة ContentStudio تحت AQLIYA. الذكاء يساعد — الإنسان يقرر — الدليل يحكم.",
    );
  doc.text(
    "Generated by AQLIYA ContentStudio. AI assists. Humans decide. Evidence governs.",
  );

  // ─── Page numbers ───
  const range = doc.bufferedPageRange();
  if (range && range.count > 0) {
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).fillColor("#888888").font("Helvetica");
      doc.text(
        `AQLIYA ContentStudio — Page ${i + 1}`,
        50,
        doc.page.height - 50 - 10,
        { align: "center", width: 495 },
      );
    }
  }

  doc.end();
  await endPromise;

  const buffer = Buffer.concat(chunks);

  return {
    format: "pdf",
    filename: `content_studio_${input.contentId.substring(0, 8)}.pdf`,
    mimeType: "application/pdf",
    content: buffer,
  };
}
