export const CS_STRINGS = {
  error: {
    WORKSPACE_NOT_FOUND: 'Content workspace not found',
    WORKSPACE_NAME_REQUIRED: 'Workspace name is required',
    ORG_ID_REQUIRED: 'Organization ID is required',
    CONTENT_NOT_FOUND: 'Content item not found',
    TEMPLATE_NOT_FOUND: 'Content template not found',
    TITLE_REQUIRED: 'Content title is required',
    INVALID_TRANSITION: 'Content status does not allow this action',
    REASON_REQUIRED: 'Reason is required for rejection',
    NOT_IN_REVIEW: 'Content must be in review for this action',
    NOT_APPROVED: 'Content must be approved before publishing',
    NOT_PUBLISHED: 'Content must be published before archiving',
    VERSION_NOT_FOUND: 'Content version not found',
    WORKSPACE_ID_REQUIRED: 'Workspace ID is required',
    TEMPLATE_NAME_REQUIRED: 'Template name is required',
    BODY_TEMPLATE_REQUIRED: 'Body template is required',
    CREATE_FAILED: 'Failed to create content',
    FETCH_FAILED: 'Failed to fetch content data',
  },
  event: {
    WORKSPACE_CREATED: 'Content workspace created',
    WORKSPACE_UPDATED: 'Content workspace updated',
    CONTENT_CREATED: 'Content item created',
    CONTENT_UPDATED: 'Content item updated',
    SUBMITTED_FOR_REVIEW: 'Content submitted for review',
    CONTENT_APPROVED: 'Content approved',
    CONTENT_REJECTED: 'Content rejected',
    CONTENT_PUBLISHED: 'Content published',
    CONTENT_ARCHIVED: 'Content archived',
    TEMPLATE_CREATED: 'Content template created',
    VERSION_RESTORED: 'Content restored to previous version',
    CONTENT_CREATED_FROM_TEMPLATE: 'Content created from template',
  },
  ar: {
    error: {
      WORKSPACE_NOT_FOUND: 'مساحة العمل غير موجودة',
      CONTENT_NOT_FOUND: 'المحتوى غير موجود',
      TEMPLATE_NOT_FOUND: 'القالب غير موجود',
      TITLE_REQUIRED: 'عنوان المحتوى مطلوب',
      INVALID_TRANSITION: 'حالة المحتوى لا تسمح بهذا الإجراء',
      REASON_REQUIRED: 'السبب مطلوب للرفض',
      NOT_IN_REVIEW: 'يجب أن يكون المحتوى قيد المراجعة لهذا الإجراء',
      NOT_APPROVED: 'يجب الموافقة على المحتوى قبل النشر',
      NOT_PUBLISHED: 'يجب نشر المحتوى قبل الأرشفة',
      VERSION_NOT_FOUND: 'إصدار المحتوى غير موجود',
    },
    event: {
      SUBMITTED_FOR_REVIEW: 'تم تقديم المحتوى للمراجعة',
      CONTENT_APPROVED: 'تمت الموافقة على المحتوى',
      CONTENT_REJECTED: 'تم رفض المحتوى',
      CONTENT_PUBLISHED: 'تم نشر المحتوى',
      CONTENT_ARCHIVED: 'تم أرشفة المحتوى',
    },
  },
} as const
